In [3]:
import pandas as pd
import numpy as np

In [4]:
pwd

'D:\\我的文档\\Documents'

In [5]:
ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 1022-7BCD

 D:\我的文档\Documents 的目录

2016/10/17  08:07    <DIR>          .
2016/10/17  08:07    <DIR>          ..
2016/10/16  19:11    <DIR>          .ipynb_checkpoints
2016/10/10  17:08             8,523 .RData
2016/10/14  23:32            13,233 .Rhistory
2016/10/10  19:22    <DIR>          My eBooks
2016/10/17  08:07           415,882 Python第二节课.ipynb
2016/10/16  19:09           820,075 Python第一节课 .ipynb
2016/10/16  15:36           333,944 Python修改函数+数据结构.pdf
2016/10/16  19:20    <DIR>          Python学习
2016/09/09  20:07    <DIR>          QQPCMgr
2016/09/18  21:27    <DIR>          SPSSInc
2016/10/16  16:26    <DIR>          Tencent Files
2016/09/10  07:58    <DIR>          WeChat Files
2016/09/23  19:40    <DIR>          暴风影视库
2016/10/16  19:15    <DIR>          第一天课程20161015
2016/09/25  23:03    <DIR>          美图图库
               5 个文件      1,591,657 字节
              12 个目录 99,636,895,744 可用字节

In [13]:
df = pd.read_csv('Python学习/Python第二节课/adultTest.csv')

In [24]:
df.head()

              age          workclass  fnlwgt   education  education-num  \
race  sex
White Male     39          State-gov   77516   Bachelors             13
      Male     50   Self-emp-not-inc   83311   Bachelors             13
      Male     38            Private  215646     HS-grad              9
Black Male     53            Private  234721        11th              7
      Female   28            Private  338409   Bachelors             13

                   marital-status          occupation    relationship   race  \
race  sex
White Male          Never-married        Adm-clerical   Not-in-family  White
      Male     Married-civ-spouse     Exec-managerial         Husband  White
      Male               Divorced   Handlers-cleaners   Not-in-family  White
Black Male     Married-civ-spouse   Handlers-cleaners         Husband  Black
      Female   Married-civ-spouse      Prof-specialty            Wife  Black

                 sex  capital-gain  capital-loss  hours-per-week  \
race  sex
White Male      Male          2174             0              40
      Male      Male             0             0              13
      Male      Male             0             0              40
Black Male      Male             0             0              40
      Female  Female             0             0              40

              native-country   class
race  sex
White Male     United-States   <=50K
      Male     United-States   <=50K
      Male     United-States   <=50K
Black Male     United-States   <=50K
      Female            Cuba   <=50K

In [25]:
df.set_index(['race','sex'],inplace=True,drop=False)

In [26]:
df.head()

              age          workclass  fnlwgt   education  education-num  \
race  sex
White Male     39          State-gov   77516   Bachelors             13
      Male     50   Self-emp-not-inc   83311   Bachelors             13
      Male     38            Private  215646     HS-grad              9
Black Male     53            Private  234721        11th              7
      Female   28            Private  338409   Bachelors             13

                   marital-status          occupation    relationship   race  \
race  sex
White Male          Never-married        Adm-clerical   Not-in-family  White
      Male     Married-civ-spouse     Exec-managerial         Husband  White
      Male               Divorced   Handlers-cleaners   Not-in-family  White
Black Male     Married-civ-spouse   Handlers-cleaners         Husband  Black
      Female   Married-civ-spouse      Prof-specialty            Wife  Black

                 sex  capital-gain  capital-loss  hours-per-week  \
race  sex
White Male      Male          2174             0              40
      Male      Male             0             0              13
      Male      Male             0             0              40
Black Male      Male             0             0              40
      Female  Female             0             0              40

              native-country   class
race  sex
White Male     United-States   <=50K
      Male     United-States   <=50K
      Male     United-States   <=50K
Black Male     United-States   <=50K
      Female            Cuba   <=50K

In [9]:
df.index  # 层次索引，多重索引

MultiIndex(levels=[['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other', 'White'], ['Female', 'Male']],

In [14]:
df.loc["White"]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
sex,,,,,,,,,,,,,,,
Male,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
Male,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
Male,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
Female,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
Male,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
Female,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
Male,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
Female,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
Male,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
Male,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
Male,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
Female,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
Male,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
Male,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
Female,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
Male,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
Male,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
Male,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
Male,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
Male,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
Male,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
Male,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
Male,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
Male,21,Private,197200,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
Female,19,Private,544091,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
Male,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
Male,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
Male,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
Male,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
Male,24,Private,172987,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Male,58,Private,147707,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
Male,30,Private,77266,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,55,United-States,<=50K
Female,26,Private,191648,Assoc-acdm,12,Never-married,Machine-op-inspct,Other-relative,White,Female,0,0,15,United-States,<=50K
Female,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K
Male,32,Private,211349,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
Male,22,Private,203715,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
Female,31,Private,292592,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
Female,29,Private,125976,HS-grad,9,Separated,Sales,Unmarried,White,Female,0,0,35,United-States,<=50K
Female,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
Male,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
Female,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
Female,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
Male,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
Female,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
Male,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
Female,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
Female,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
Female,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
Male,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
Male,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
Female,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
Male,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
Male,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
Male,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
Male,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
Female,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
Male,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
Female,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
Male,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
Female,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [29]:
df.loc["White"]["race"]  # 选取两列

sex
Male      White
Male      White
Male      White
Female    White
Male      White
Female    White
Male      White
Female    White
Male      White
Male      White
Male      White
Female    White
Male      White
Male      White
Female    White
Male      White
Male      White
Male      White
Male      White
Male      White
Male      White
Male      White
Male      White
Male      White
Female    White
Male      White
Male      White
Male      White
Male      White
Male      White
          ...
Male      White
Male      White
Female    White
Female    White
Male      White
Male      White
Female    White
Female    White
Female    White
Male      White
Female    White
Female    White
Male      White
Female    White
Male      White
Female    White
Female    White
Female    White
Male      White
Male      White
Female    White
Male      White
Male      White
Male      White
Male      White
Female    White
Male      White
Female    White
Male      White
Female    White
Name: race, dtype: object

In [28]:
df.loc["Male"]

KeyError: 'the label [Male] is not in the [index]'

多重索引（层次索引）的时候，如果你loc里什么没有详细的设置，直接写一个名称的话，它默认的是第0个level上的索引。male在第1个level中，所以它找不到。

In [30]:
df.index.get_level_values(0) # level=0所有index的值

Index(['White', 'White', 'White', 'Black', 'Black', 'White', 'Black', 'White',
       'White', 'White',
       ...
       'Amer-Indian-Eskimo', 'White', 'Asian-Pac-Islander', 'White', 'White',
       'White', 'White', 'White', 'White', 'White'],
      dtype='object', name='race', length=32561)

In [31]:
df.loc["White","Male"]  #若我们选取除了索引外的某一列怎么办呢

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  if __name__ == '__main__':

            age          workclass  fnlwgt      education  education-num  \
race  sex
White Male   39          State-gov   77516      Bachelors             13
      Male   50   Self-emp-not-inc   83311      Bachelors             13
      Male   38            Private  215646        HS-grad              9
      Male   52   Self-emp-not-inc  209642        HS-grad              9
      Male   42            Private  159449      Bachelors             13
      Male   25   Self-emp-not-inc  176756        HS-grad              9
      Male   32            Private  186824        HS-grad              9
      Male   38            Private   28887           11th              7
      Male   40            Private  193524      Doctorate             16
      Male   43            Private  117037           11th              7
      Male   56          Local-gov  216851      Bachelors             13
      Male   19            Private  168294        HS-grad              9
      Male   39            Private  367260        HS-grad              9
      Male   49            Private  193366        HS-grad              9
      Male   23          Local-gov  190709     Assoc-acdm             12
      Male   45            Private  386940      Bachelors             13
      Male   30        Federal-gov   59951   Some-college             10
      Male   48            Private  242406           11th              7
      Male   21            Private  197200   Some-college             10
      Male   31            Private   84154   Some-college             10
      Male   48   Self-emp-not-inc  265477     Assoc-acdm             12
      Male   31            Private  507875            9th              5
      Male   53   Self-emp-not-inc   88506      Bachelors             13
      Male   24            Private  172987      Bachelors             13
      Male   25            Private  289980        HS-grad              9
      Male   53            Private  144361        HS-grad              9
      Male   41          State-gov  101603      Assoc-voc             11
      Male   29            Private  271466      Assoc-voc             11
      Male   50        Federal-gov  251585      Bachelors             13
      Male   47       Self-emp-inc  109832        HS-grad              9
...         ...                ...     ...            ...            ...
      Male   26            Private  179010   Some-college             10
      Male   18            Private  436163           11th              7
      Male   57            Private  153918        HS-grad              9
      Male   34            Private   60567           11th              7
      Male   71            Private  138145            9th              5
      Male   35          Local-gov   79649      Bachelors             13
      Male   47            Private  312088        HS-grad              9
      Male   38            Private   32916      Assoc-voc             11
      Male   50            Private  302372      Bachelors             13
      Male   39            Private  107302        HS-grad              9
      Male   20            Private  270436        HS-grad              9
      Male   66        Federal-gov   47358           10th              6
      Male   36            Private  131459        7th-8th              4
      Male   57          Local-gov  110417        HS-grad              9
      Male   46            Private  364548   Some-college             10
      Male   58            Private  147707           11th              7
      Male   30            Private   77266        HS-grad              9
      Male   32            Private  211349           10th              6
      Male   22            Private  203715   Some-college             10
      Male   34            Private  204461      Doctorate             16
      Male   71                  ?  287372      Doctorate             16
      Male   72                  ?  129912        HS-grad              9
      Male   43            Private  260761        HS-grad              9
      Male   65   Self-emp-not-inc   99359    Prof-school             15
      Male   43   Self-emp-not-inc   27242   Some-college             10
      Male   43            Private   84661      Assoc-voc             11
      Male   53            Private  321865        Masters             14
      Male   22            Private  310152   Some-college             10
      Male   40            Private  154374        HS-grad              9
      Male   22            Private  201490        HS-grad              9

                 marital-status          occupation    relationship   race  \
race  sex
White Male        Never-married        Adm-clerical   Not-in-family  White
      Male   Married-civ-spouse     Exec-managerial         Husband  White
      Male             Divorced   Handlers-cleaners   Not-in-family  White
      Male   Married-civ-spouse     Exec-managerial         Husband  White
      Male   Married-civ-spouse     Exec-managerial         Husband  White
      Male        Never-married     Farming-fishing       Own-child  White
      Male        Never-married   Machine-op-inspct       Unmarried  White
      Male   Married-civ-spouse               Sales         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse    Transport-moving         Husband  White
      Male   Married-civ-spouse        Tech-support         Husband  White
      Male        Never-married        Craft-repair       Own-child  White
      Male             Divorced     Exec-managerial   Not-in-family  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male        Never-married     Protective-serv   Not-in-family  White
      Male             Divorced     Exec-managerial       Own-child  White
      Male   Married-civ-spouse        Adm-clerical       Own-child  White
      Male        Never-married   Machine-op-inspct       Unmarried  White
      Male        Never-married   Machine-op-inspct       Own-child  White
      Male   Married-civ-spouse               Sales         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse   Machine-op-inspct         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse        Tech-support         Husband  White
      Male        Never-married   Handlers-cleaners   Not-in-family  White
      Male   Married-civ-spouse   Machine-op-inspct         Husband  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male        Never-married      Prof-specialty   Not-in-family  White
      Male             Divorced     Exec-managerial   Not-in-family  White
      Male             Divorced     Exec-managerial   Not-in-family  White
...                         ...                 ...             ...    ...
      Male        Never-married        Craft-repair   Not-in-family  White
      Male        Never-married      Prof-specialty       Own-child  White
      Male   Married-civ-spouse    Transport-moving         Husband  White
      Male             Divorced    Transport-moving       Unmarried  White
      Male   Married-civ-spouse       Other-service         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male        Never-married   Machine-op-inspct       Own-child  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse     Exec-managerial         Husband  White
      Male   Married-civ-spouse               Sales         Husband  White
      Male             Divorced    Transport-moving   Not-in-family  White
      Male   Married-civ-spouse    Transport-moving         Husband  White
      Male        Never-married        Adm-clerical       Own-child  White
      Male   Married-civ-spouse      Prof-specialty         Husband  White
      Male   Married-civ-spouse                   ?         Husband  White
      Male   Married-civ-spouse                   ?         Husband  White
      Male   Married-civ-spouse   Machine-op-inspct         Husband  White
      Male        Never-married      Prof-specialty   Not-in-family  White
      Male   Married-civ-spouse        Craft-repair         Husband  White
      Male   Married-civ-spouse               Sales         Husband  White
      Male   Married-civ-spouse     Exec-managerial         Husband  White
      Male        Never-married     Protective-serv   Not-in-family  White
      Male   Married-civ-spouse   Machine-op-inspct         Husband  White
      Male        Never-married        Adm-clerical       Own-child  White

             sex  capital-gain  capital-loss  hours-per-week  native-country  \
race  sex
White Male  Male          2174             0              40   United-States
      Male  Male             0             0              13   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              45   United-States
      Male  Male          5178             0              40   United-States
      Male  Male             0             0              35   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              50   United-States
      Male  Male             0             0              60   United-States
      Male  Male             0          2042              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              80   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              52   United-States
      Male  Male             0          1408              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              40     Puerto-Rico
      Male  Male             0             0              40   United-States
      Male  Male             0             0              38               ?
      Male  Male             0             0              40   United-States
      Male  Male             0             0              43   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              50   United-States
      Male  Male             0             0              35   United-States
      Male  Male             0             0              38   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              43   United-States
      Male  Male             0             0              55   United-States
      Male  Male             0             0              60   United-States
...          ...           ...           ...             ...             ...
      Male  Male             0             0              65   United-States
      Male  Male             0             0              20   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0           880              60   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              50   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              55   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              45               ?
      Male  Male             0             0              40   United-States
      Male  Male          3471             0              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male         99999             0              40   United-States
      Male  Male             0             0              48   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              55   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              60   United-States
      Male  Male             0             0              10   United-States
      Male  Male             0             0              25   United-States
      Male  Male             0             0              40          Mexico
      Male  Male          1086             0              60   United-States
      Male  Male             0             0              50   United-States
      Male  Male             0             0              45   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              40   United-States
      Male  Male             0             0              20   United-States

             class
race  sex
White Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male   <=50K
...            ...
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male    >50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male   <=50K
      Male    >50K
      Male   <=50K
      Male    >50K
      Male   <=50K

[19174 rows x 15 columns]

**loc（ ，）逗号是区分索引与列名的**

# slice

In [ ]:
[1,2,3,4,5] 
slice(2,5)    # 2,5指的是切片从2到5
slice(None)  # 意味着全选

#### 选取sex是male的数据，race不管  （race与sex是索引的情况下）

In [32]:
df.loc[(slice(None),["Male"])]

KeyError: "None of [['Male']] are in the [columns]"

In [25]:
df.loc[(slice(None),["Male"]),:]  # 报错的原因是没有排序

KeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (2), lexsort depth (0)'

### loc在多重索引里面，如果你要用slice的话，你必须得指定列名。单层索引就可忽略。            
### 用slice之前要排序！

In [33]:
df.sort_index(inplace = True,ascending= True) # ascending默认值为True,升序

In [34]:
df.loc[(slice(None),["Male"]),:] # 列名为：，意味着列全选

                         age          workclass  fnlwgt      education  \
race               sex
Amer-Indian-Eskimo Male   34            Private  245487        7th-8th
                   Male   51            Private   56915        HS-grad
                   Male   20            Private   27337        HS-grad
                   Male   29            Private  182521        HS-grad
                   Male   27                  ?   90270     Assoc-acdm
                   Male   48   Self-emp-not-inc  243631   Some-college
                   Male   46            Private  134727           11th
                   Male   40            Private  100584           10th
                   Male   27            Private   23940        HS-grad
                   Male   53            Private  121618        7th-8th
                   Male   20            Private  137651   Some-college
                   Male   31            Private  100997   Some-college
                   Male   52   Self-emp-not-inc  242341        7th-8th
                   Male   56        Federal-gov  162137        HS-grad
                   Male   42            Private  245626        HS-grad
                   Male   51            Private  209912      Bachelors
                   Male   35            Private   25955           11th
                   Male   31            Private  197023      Assoc-voc
                   Male   28            Private  259351           10th
                   Male   44            Private  100584        HS-grad
                   Male   41            Private  113555   Some-college
                   Male   45   Self-emp-not-inc  239093   Some-college
                   Male   20                  ?   34862   Some-college
                   Male   28            Private   25955      Assoc-voc
                   Male   43            Private  161226      Bachelors
                   Male   29            Private  120986        HS-grad
                   Male   41            Private  147314        HS-grad
                   Male   45            Private   26781        HS-grad
                   Male   42            Private  108506        HS-grad
                   Male   33            Private  163392        HS-grad
...                      ...                ...     ...            ...
White              Male   26            Private  179010   Some-college
                   Male   18            Private  436163           11th
                   Male   57            Private  153918        HS-grad
                   Male   34            Private   60567           11th
                   Male   71            Private  138145            9th
                   Male   35          Local-gov   79649      Bachelors
                   Male   47            Private  312088        HS-grad
                   Male   38            Private   32916      Assoc-voc
                   Male   50            Private  302372      Bachelors
                   Male   39            Private  107302        HS-grad
                   Male   20            Private  270436        HS-grad
                   Male   66        Federal-gov   47358           10th
                   Male   36            Private  131459        7th-8th
                   Male   57          Local-gov  110417        HS-grad
                   Male   46            Private  364548   Some-college
                   Male   58            Private  147707           11th
                   Male   30            Private   77266        HS-grad
                   Male   32            Private  211349           10th
                   Male   22            Private  203715   Some-college
                   Male   34            Private  204461      Doctorate
                   Male   71                  ?  287372      Doctorate
                   Male   72                  ?  129912        HS-grad
                   Male   43            Private  260761        HS-grad
                   Male   65   Self-emp-not-inc   99359    Prof-school
                   Male   43   Self-emp-not-inc   27242   Some-college
                   Male   43            Private   84661      Assoc-voc
                   Male   53            Private  321865        Masters
                   Male   22            Private  310152   Some-college
                   Male   40            Private  154374        HS-grad
                   Male   22            Private  201490        HS-grad

                         education-num       marital-status  \
race               sex
Amer-Indian-Eskimo Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9        Never-married
                   Male              9        Never-married
                   Male             12   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male              7             Divorced
                   Male              6             Divorced
                   Male              9        Never-married
                   Male              4        Never-married
                   Male             10        Never-married
                   Male             10   Married-civ-spouse
                   Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             13             Divorced
                   Male              7        Never-married
                   Male             11   Married-civ-spouse
                   Male              6        Never-married
                   Male              9   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male             10        Never-married
                   Male             11             Divorced
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
...                                ...                  ...
White              Male             10        Never-married
                   Male              7        Never-married
                   Male              9   Married-civ-spouse
                   Male              7             Divorced
                   Male              5   Married-civ-spouse
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             11   Married-civ-spouse
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9        Never-married
                   Male              6   Married-civ-spouse
                   Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male              7   Married-civ-spouse
                   Male              9             Divorced
                   Male              6   Married-civ-spouse
                   Male             10        Never-married
                   Male             16   Married-civ-spouse
                   Male             16   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             15        Never-married
                   Male             10   Married-civ-spouse
                   Male             11   Married-civ-spouse
                   Male             14   Married-civ-spouse
                   Male             10        Never-married
                   Male              9   Married-civ-spouse
                   Male              9        Never-married

                                 occupation     relationship  \
race               sex
Amer-Indian-Eskimo Male    Transport-moving          Husband
                   Male        Craft-repair          Husband
                   Male   Handlers-cleaners        Own-child
                   Male        Craft-repair    Not-in-family
                   Male                   ?        Own-child
                   Male        Craft-repair          Husband
                   Male   Machine-op-inspct        Unmarried
                   Male        Craft-repair    Not-in-family
                   Male   Handlers-cleaners   Other-relative
                   Male    Transport-moving    Not-in-family
                   Male   Machine-op-inspct        Own-child
                   Male      Prof-specialty          Husband
                   Male        Craft-repair          Husband
                   Male    Transport-moving          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial    Not-in-family
                   Male       Other-service        Unmarried
                   Male   Machine-op-inspct          Husband
                   Male       Other-service   Other-relative
                   Male   Machine-op-inspct          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial          Husband
                   Male                   ?        Own-child
                   Male        Craft-repair    Not-in-family
                   Male   Machine-op-inspct          Husband
                   Male    Transport-moving          Husband
                   Male               Sales          Husband
                   Male      Prof-specialty          Husband
                   Male    Transport-moving          Husband
                   Male      Prof-specialty          Husband
...                                     ...              ...
White              Male        Craft-repair    Not-in-family
                   Male      Prof-specialty        Own-child
                   Male    Transport-moving          Husband
                   Male    Transport-moving        Unmarried
                   Male       Other-service          Husband
                   Male      Prof-specialty          Husband
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male      Prof-specialty          Husband
                   Male      Prof-specialty          Husband
                   Male   Machine-op-inspct        Own-child
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial          Husband
                   Male               Sales          Husband
                   Male    Transport-moving    Not-in-family
                   Male    Transport-moving          Husband
                   Male        Adm-clerical        Own-child
                   Male      Prof-specialty          Husband
                   Male                   ?          Husband
                   Male                   ?          Husband
                   Male   Machine-op-inspct          Husband
                   Male      Prof-specialty    Not-in-family
                   Male        Craft-repair          Husband
                   Male               Sales          Husband
                   Male     Exec-managerial          Husband
                   Male     Protective-serv    Not-in-family
                   Male   Machine-op-inspct          Husband
                   Male        Adm-clerical        Own-child

                                       race   sex  capital-gain  capital-loss  \
race               sex
Amer-Indian-Eskimo Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male          7688             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male          7298             0
                   Male  Amer-Indian-Eskimo  Male          3137             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
...                                     ...   ...           ...           ...
White              Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0           880
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male          3471             0
                   Male               White  Male             0             0
                   Male               White  Male         99999             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male          1086             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0

                         hours-per-week  native-country   class
race               sex
Amer-Indian-Eskimo Male              45          Mexico   <=50K
                   Male              40   United-States   <=50K
                   Male              48   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States    >50K
                   Male              43         Germany   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40          Mexico   <=50K
                   Male              40   United-States   <=50K
                   Male              50   United-States    >50K
                   Male              40   United-States   <=50K
                   Male              72   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              65   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male               8   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              48   United-States    >50K
...                                 ...             ...     ...
White              Male              65   United-States   <=50K
                   Male              20   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              55   United-States    >50K
                   Male              40   United-States   <=50K
                   Male              45               ?    >50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States    >50K
                   Male              48   United-States    >50K
                   Male              40   United-States   <=50K

In [35]:
df.race.value_counts()  # 根据种族选择计数

White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64

##### 我们现只想选出race in（white,black) and sex = female

In [36]:
df.loc[[["White","Black"],["Female"]],:]
#race不是选择white就是black，此时不适合区间选择
#列表的方式指定每一层索引上你要选择的数据

TypeError: '['White', 'Black']' is an invalid key

In [37]:
df.loc[(["White","Black"],["Female"]),:] #这种的索引也要排序，不然容易报错！

              age          workclass  fnlwgt      education  education-num  \
race  sex
Black Female   28            Private  338409      Bachelors             13
      Female   49            Private  160187            9th              5
      Female   54            Private  302146        HS-grad              9
      Female   31            Private  309974      Bachelors             13
      Female   28            Private  212563   Some-college             10
      Female   46            Private  146195     Assoc-acdm             12
      Female   31            Private  185814        HS-grad              9
      Female   38            Private  155222   Some-college             10
      Female   41            Private  130408        HS-grad              9
      Female   42            Private  390781      Bachelors             13
      Female   59          Local-gov  171328           10th              6
      Female   34            Private  175413     Assoc-acdm             12
      Female   27            Private  248402      Bachelors             13
      Female   19                  ?  860348   Some-college             10
      Female   36   Self-emp-not-inc  205607      Bachelors             13
      Female   23                  ?  211601      Assoc-voc             11
      Female   22          State-gov  293364   Some-college             10
      Female   41          Local-gov   42346   Some-college             10
      Female   24            Private  241951        HS-grad              9
      Female   44            Private  290521        HS-grad              9
      Female   19            Private  206399        HS-grad              9
      Female   25            Private  189775   Some-college             10
      Female   47          Local-gov  543162        HS-grad              9
      Female   53                  ?  251804        5th-6th              3
      Female   57            Private  190942        1st-4th              2
      Female   34                  ?  190027        HS-grad              9
      Female   35            Private  229328        HS-grad              9
      Female   33        Federal-gov  319560      Assoc-voc             11
      Female   24            Private   82804        HS-grad              9
      Female   48            Private   45612        HS-grad              9
...           ...                ...     ...            ...            ...
White Female   66            Private  269665        HS-grad              9
      Female   58       Self-emp-inc  181974      Doctorate             16
      Female   50            Private  485710      Doctorate             16
      Female   41        Federal-gov  160467        Masters             14
      Female   52            Private  301229      Assoc-voc             11
      Female   27            Private  155382   Some-college             10
      Female   48            Private  268083   Some-college             10
      Female   28            Private  113987        HS-grad              9
      Female   24            Private  381895           11th              7
      Female   34            Private  321709        HS-grad              9
      Female   50            Private  208630        Masters             14
      Female   32            Private  192965        HS-grad              9
      Female   46            Private   42972        Masters             14
      Female   30            Private  176175      Assoc-voc             11
      Female   27            Private  177398        HS-grad              9
      Female   26            Private  191648     Assoc-acdm             12
      Female   81                  ?  120478      Assoc-voc             11
      Female   31            Private  292592        HS-grad              9
      Female   29            Private  125976        HS-grad              9
      Female   35                  ?  320084      Bachelors             13
      Female   37            Private  179137   Some-college             10
      Female   34            Private  160216      Bachelors             13
      Female   45          State-gov  252208        HS-grad              9
      Female   45          Local-gov  119199     Assoc-acdm             12
      Female   39          Local-gov  111499     Assoc-acdm             12
      Female   37            Private  198216     Assoc-acdm             12
      Female   43          State-gov  255835   Some-college             10
      Female   27            Private  257302     Assoc-acdm             12
      Female   58            Private  151910        HS-grad              9
      Female   52       Self-emp-inc  287927        HS-grad              9

                      marital-status          occupation     relationship  \
race  sex
Black Female      Married-civ-spouse      Prof-specialty             Wife
      Female   Married-spouse-absent       Other-service    Not-in-family
      Female               Separated       Other-service        Unmarried
      Female               Separated               Sales        Own-child
      Female                Divorced   Machine-op-inspct        Unmarried
      Female                Divorced        Tech-support    Not-in-family
      Female           Never-married    Transport-moving        Unmarried
      Female                Divorced   Machine-op-inspct    Not-in-family
      Female                Divorced               Sales        Unmarried
      Female      Married-civ-spouse        Adm-clerical             Wife
      Female                 Widowed       Other-service        Unmarried
      Female                Divorced               Sales        Unmarried
      Female           Never-married        Tech-support        Unmarried
      Female           Never-married                   ?        Own-child
      Female                Divorced      Prof-specialty    Not-in-family
      Female           Never-married                   ?        Own-child
      Female           Never-married     Protective-serv        Own-child
      Female                Divorced       Other-service    Not-in-family
      Female           Never-married   Handlers-cleaners        Unmarried
      Female                 Widowed     Exec-managerial        Unmarried
      Female           Never-married   Machine-op-inspct        Own-child
      Female   Married-spouse-absent        Adm-clerical        Own-child
      Female               Separated        Adm-clerical        Unmarried
      Female                 Widowed                   ?        Unmarried
      Female                 Widowed     Priv-house-serv    Not-in-family
      Female           Never-married                   ?        Unmarried
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female                Divorced        Craft-repair        Unmarried
      Female           Never-married   Handlers-cleaners        Unmarried
      Female           Never-married        Adm-clerical        Unmarried
...                              ...                 ...              ...
White Female                 Widowed     Exec-managerial    Not-in-family
      Female           Never-married      Prof-specialty    Not-in-family
      Female                Divorced      Prof-specialty    Not-in-family
      Female                Divorced      Prof-specialty        Unmarried
      Female               Separated               Sales        Unmarried
      Female           Never-married       Other-service    Not-in-family
      Female                Divorced     Exec-managerial    Not-in-family
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female                Divorced   Machine-op-inspct        Unmarried
      Female           Never-married       Other-service    Not-in-family
      Female                Divorced               Sales    Not-in-family
      Female               Separated               Sales    Not-in-family
      Female      Married-civ-spouse      Prof-specialty             Wife
      Female                Divorced        Adm-clerical        Unmarried
      Female           Never-married       Other-service        Unmarried
      Female           Never-married   Machine-op-inspct   Other-relative
      Female                Divorced                   ?        Unmarried
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female               Separated               Sales        Unmarried
      Female      Married-civ-spouse                   ?             Wife
      Female                Divorced        Adm-clerical        Unmarried
      Female           Never-married     Exec-managerial    Not-in-family
      Female               Separated        Adm-clerical        Own-child
      Female                Divorced      Prof-specialty        Unmarried
      Female      Married-civ-spouse        Adm-clerical             Wife
      Female                Divorced        Tech-support    Not-in-family
      Female                Divorced        Adm-clerical   Other-relative
      Female      Married-civ-spouse        Tech-support             Wife
      Female                 Widowed        Adm-clerical        Unmarried
      Female      Married-civ-spouse     Exec-managerial             Wife

               race     sex  capital-gain  capital-loss  hours-per-week  \
race  sex
Black Female  Black  Female             0             0              40
      Female  Black  Female             0             0              16
      Female  Black  Female             0             0              20
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              25
      Female  Black  Female             0             0              36
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              28
      Female  Black  Female             0             0              38
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              45
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              25
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              15
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              24
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              20
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              37
...             ...     ...           ...           ...             ...
White Female  White  Female             0             0              25
      Female  White  Female             0             0              99
      Female  White  Female             0             0              50
      Female  White  Female          1506             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              25
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              28
      Female  White  Female             0             0              50
      Female  White  Female             0             0              45
      Female  White  Female             0             0              22
      Female  White  Female             0             0              24
      Female  White  Female             0             0              64
      Female  White  Female             0             0              15
      Female  White  Female             0             0               1
      Female  White  Female             0             0              40
      Female  White  Female             0             0              35
      Female  White  Female             0             0              55
      Female  White  Female             0             0              39
      Female  White  Female             0             0              55
      Female  White  Female             0             0              40
      Female  White  Female             0             0              48
      Female  White  Female             0             0              20
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              38
      Female  White  Female             0             0              40
      Female  White  Female         15024             0              40

              native-country   class
race  sex
Black Female            Cuba   <=50K
      Female         Jamaica   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
...                      ...     ...
White Female   United-States   <=50K
      Female               ?   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female               ?   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K

[10197 rows x 15 columns]

In [38]:
df.loc[(["White","Black"],["Female"]),:]

              age          workclass  fnlwgt      education  education-num  \
race  sex
Black Female   28            Private  338409      Bachelors             13
      Female   49            Private  160187            9th              5
      Female   54            Private  302146        HS-grad              9
      Female   31            Private  309974      Bachelors             13
      Female   28            Private  212563   Some-college             10
      Female   46            Private  146195     Assoc-acdm             12
      Female   31            Private  185814        HS-grad              9
      Female   38            Private  155222   Some-college             10
      Female   41            Private  130408        HS-grad              9
      Female   42            Private  390781      Bachelors             13
      Female   59          Local-gov  171328           10th              6
      Female   34            Private  175413     Assoc-acdm             12
      Female   27            Private  248402      Bachelors             13
      Female   19                  ?  860348   Some-college             10
      Female   36   Self-emp-not-inc  205607      Bachelors             13
      Female   23                  ?  211601      Assoc-voc             11
      Female   22          State-gov  293364   Some-college             10
      Female   41          Local-gov   42346   Some-college             10
      Female   24            Private  241951        HS-grad              9
      Female   44            Private  290521        HS-grad              9
      Female   19            Private  206399        HS-grad              9
      Female   25            Private  189775   Some-college             10
      Female   47          Local-gov  543162        HS-grad              9
      Female   53                  ?  251804        5th-6th              3
      Female   57            Private  190942        1st-4th              2
      Female   34                  ?  190027        HS-grad              9
      Female   35            Private  229328        HS-grad              9
      Female   33        Federal-gov  319560      Assoc-voc             11
      Female   24            Private   82804        HS-grad              9
      Female   48            Private   45612        HS-grad              9
...           ...                ...     ...            ...            ...
White Female   66            Private  269665        HS-grad              9
      Female   58       Self-emp-inc  181974      Doctorate             16
      Female   50            Private  485710      Doctorate             16
      Female   41        Federal-gov  160467        Masters             14
      Female   52            Private  301229      Assoc-voc             11
      Female   27            Private  155382   Some-college             10
      Female   48            Private  268083   Some-college             10
      Female   28            Private  113987        HS-grad              9
      Female   24            Private  381895           11th              7
      Female   34            Private  321709        HS-grad              9
      Female   50            Private  208630        Masters             14
      Female   32            Private  192965        HS-grad              9
      Female   46            Private   42972        Masters             14
      Female   30            Private  176175      Assoc-voc             11
      Female   27            Private  177398        HS-grad              9
      Female   26            Private  191648     Assoc-acdm             12
      Female   81                  ?  120478      Assoc-voc             11
      Female   31            Private  292592        HS-grad              9
      Female   29            Private  125976        HS-grad              9
      Female   35                  ?  320084      Bachelors             13
      Female   37            Private  179137   Some-college             10
      Female   34            Private  160216      Bachelors             13
      Female   45          State-gov  252208        HS-grad              9
      Female   45          Local-gov  119199     Assoc-acdm             12
      Female   39          Local-gov  111499     Assoc-acdm             12
      Female   37            Private  198216     Assoc-acdm             12
      Female   43          State-gov  255835   Some-college             10
      Female   27            Private  257302     Assoc-acdm             12
      Female   58            Private  151910        HS-grad              9
      Female   52       Self-emp-inc  287927        HS-grad              9

                      marital-status          occupation     relationship  \
race  sex
Black Female      Married-civ-spouse      Prof-specialty             Wife
      Female   Married-spouse-absent       Other-service    Not-in-family
      Female               Separated       Other-service        Unmarried
      Female               Separated               Sales        Own-child
      Female                Divorced   Machine-op-inspct        Unmarried
      Female                Divorced        Tech-support    Not-in-family
      Female           Never-married    Transport-moving        Unmarried
      Female                Divorced   Machine-op-inspct    Not-in-family
      Female                Divorced               Sales        Unmarried
      Female      Married-civ-spouse        Adm-clerical             Wife
      Female                 Widowed       Other-service        Unmarried
      Female                Divorced               Sales        Unmarried
      Female           Never-married        Tech-support        Unmarried
      Female           Never-married                   ?        Own-child
      Female                Divorced      Prof-specialty    Not-in-family
      Female           Never-married                   ?        Own-child
      Female           Never-married     Protective-serv        Own-child
      Female                Divorced       Other-service    Not-in-family
      Female           Never-married   Handlers-cleaners        Unmarried
      Female                 Widowed     Exec-managerial        Unmarried
      Female           Never-married   Machine-op-inspct        Own-child
      Female   Married-spouse-absent        Adm-clerical        Own-child
      Female               Separated        Adm-clerical        Unmarried
      Female                 Widowed                   ?        Unmarried
      Female                 Widowed     Priv-house-serv    Not-in-family
      Female           Never-married                   ?        Unmarried
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female                Divorced        Craft-repair        Unmarried
      Female           Never-married   Handlers-cleaners        Unmarried
      Female           Never-married        Adm-clerical        Unmarried
...                              ...                 ...              ...
White Female                 Widowed     Exec-managerial    Not-in-family
      Female           Never-married      Prof-specialty    Not-in-family
      Female                Divorced      Prof-specialty    Not-in-family
      Female                Divorced      Prof-specialty        Unmarried
      Female               Separated               Sales        Unmarried
      Female           Never-married       Other-service    Not-in-family
      Female                Divorced     Exec-managerial    Not-in-family
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female                Divorced   Machine-op-inspct        Unmarried
      Female           Never-married       Other-service    Not-in-family
      Female                Divorced               Sales    Not-in-family
      Female               Separated               Sales    Not-in-family
      Female      Married-civ-spouse      Prof-specialty             Wife
      Female                Divorced        Adm-clerical        Unmarried
      Female           Never-married       Other-service        Unmarried
      Female           Never-married   Machine-op-inspct   Other-relative
      Female                Divorced                   ?        Unmarried
      Female      Married-civ-spouse   Machine-op-inspct             Wife
      Female               Separated               Sales        Unmarried
      Female      Married-civ-spouse                   ?             Wife
      Female                Divorced        Adm-clerical        Unmarried
      Female           Never-married     Exec-managerial    Not-in-family
      Female               Separated        Adm-clerical        Own-child
      Female                Divorced      Prof-specialty        Unmarried
      Female      Married-civ-spouse        Adm-clerical             Wife
      Female                Divorced        Tech-support    Not-in-family
      Female                Divorced        Adm-clerical   Other-relative
      Female      Married-civ-spouse        Tech-support             Wife
      Female                 Widowed        Adm-clerical        Unmarried
      Female      Married-civ-spouse     Exec-managerial             Wife

               race     sex  capital-gain  capital-loss  hours-per-week  \
race  sex
Black Female  Black  Female             0             0              40
      Female  Black  Female             0             0              16
      Female  Black  Female             0             0              20
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              25
      Female  Black  Female             0             0              36
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              28
      Female  Black  Female             0             0              38
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              45
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              25
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              15
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              24
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              20
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              30
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              40
      Female  Black  Female             0             0              37
...             ...     ...           ...           ...             ...
White Female  White  Female             0             0              25
      Female  White  Female             0             0              99
      Female  White  Female             0             0              50
      Female  White  Female          1506             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              25
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              28
      Female  White  Female             0             0              50
      Female  White  Female             0             0              45
      Female  White  Female             0             0              22
      Female  White  Female             0             0              24
      Female  White  Female             0             0              64
      Female  White  Female             0             0              15
      Female  White  Female             0             0               1
      Female  White  Female             0             0              40
      Female  White  Female             0             0              35
      Female  White  Female             0             0              55
      Female  White  Female             0             0              39
      Female  White  Female             0             0              55
      Female  White  Female             0             0              40
      Female  White  Female             0             0              48
      Female  White  Female             0             0              20
      Female  White  Female             0             0              40
      Female  White  Female             0             0              40
      Female  White  Female             0             0              38
      Female  White  Female             0             0              40
      Female  White  Female         15024             0              40

              native-country   class
race  sex
Black Female            Cuba   <=50K
      Female         Jamaica   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
...                      ...     ...
White Female   United-States   <=50K
      Female               ?   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female               ?   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States   <=50K
      Female   United-States    >50K

[10197 rows x 15 columns]

### [ ]列表是可以增删改，( )tuple元祖有秩序的关系，(["White","Black"],['Female'])以（ ，）以逗号分开两组数据，两个level的数据。[[ ，],:]中[ ，]列表里都被视为一整体，都在第0个level

In [39]:
df.loc[(["White","Black"],['Female']),:]['race'].value_counts()

White    8642
Black    1555
Name: race, dtype: int64

 ** slice（A,B） 是区间选择，它不是对位置的选择，而是对名称进行选择，所以区间属于左闭右闭的，就是从A到B。**

## df.loc[(),:]  多层索引里传入的是元祖，不是列表！

In [45]:
df = pd.read_csv('Python学习/Python第二节课/adultTest.csv')

In [46]:
df.set_index(['race','sex'],inplace=True,drop=False,append=True)  #三个索引

In [47]:
df.head()

,,,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
,race,sex,,,,,,,,,,,,,,,
0,White,Male,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,White,Male,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,White,Male,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,Black,Male,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,Black,Female,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### 需求：对于上面的df数据集，选取0-100，并且race是white，并且sex是male的全部数据。

In [49]:
df.loc[(slice(0,100),['White'],['Male'],),:]

,,,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
,race,sex,,,,,,,,,,,,,,,
0,White,Male,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,White,Male,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,White,Male,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
7,White,Male,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
9,White,Male,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
16,White,Male,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,White,Male,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,White,Male,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
20,White,Male,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
23,White,Male,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
25,White,Male,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,White,Male,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
28,White,Male,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,White,Male,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
30,White,Male,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
32,White,Male,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
33,White,Male,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
35,White,Male,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
36,White,Male,21,Private,197200,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
38,White,Male,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
39,White,Male,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
40,White,Male,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
41,White,Male,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
42,White,Male,24,Private,172987,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
44,White,Male,25,Private,289980,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,35,United-States,<=50K
46,White,Male,53,Private,144361,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,<=50K
48,White,Male,41,State-gov,101603,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
49,White,Male,29,Private,271466,Assoc-voc,11,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,United-States,<=50K
53,White,Male,50,Federal-gov,251585,Bachelors,13,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,55,United-States,>50K
54,White,Male,47,Self-emp-inc,109832,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,60,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,White,Male,41,Private,147372,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,48,United-States,<=50K
59,White,Male,30,Private,188146,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,5013,0,40,United-States,<=50K
60,White,Male,30,Private,59496,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,2407,0,40,United-States,<=50K
61,White,Male,32,?,293936,7th-8th,4,Married-spouse-absent,?,Not-in-family,White,Male,0,0,40,?,<=50K
62,White,Male,48,Private,149640,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
63,White,Male,42,Private,116632,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
64,White,Male,29,Private,105598,Some-college,10,Divorced,Tech-support,Not-in-family,White,Male,0,0,58,United-States,<=50K
65,White,Male,36,Private,155537,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
68,White,Male,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
69,White,Male,25,?,200681,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
70,White,Male,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
72,White,Male,29,Self-emp-not-inc,162298,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,70,United-States,>50K
73,White,Male,23,Private,211678,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
74,White,Male,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
75,White,Male,27,Private,213921,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,40,Mexico,<=50K
76,White,Male,40,Private,32214,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
77,White,Male,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
79,White,Male,31,Local-gov,125927,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
80,White,Male,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
81,White,Male,52,Private,276515,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Cuba,<=50K
83,White,Male,59,Private,159937,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
86,White,Male,49,Local-gov,268234,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
87,White,Male,33,Private,202051,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
88,White,Male,30,Private,54334,9th,5,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
90,White,Male,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
94,White,Male,34,Local-gov,226296,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
95,White,Male,29,Local-gov,115585,Some-college,10,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,<=50K
96,White,Male,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
97,White,Male,37,Private,202683,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,>50K
100,White,Male,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [53]:
df.loc[(slice(0,100),['White','Black'],['Male']),:]  #在race中选只两个'White','Black'

,,,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
,race,sex,,,,,,,,,,,,,,,
0,White,Male,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,White,Male,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,White,Male,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,Black,Male,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,White,Male,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
9,White,Male,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,Black,Male,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
13,Black,Male,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
16,White,Male,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,White,Male,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,White,Male,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
20,White,Male,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
22,Black,Male,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,White,Male,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
25,White,Male,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,White,Male,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
28,White,Male,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,White,Male,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
30,White,Male,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
31,Black,Male,20,Private,266015,Some-college,10,Never-married,Sales,Own-child,Black,Male,0,0,44,United-States,<=50K
32,White,Male,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
33,White,Male,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
34,Black,Male,22,State-gov,311512,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K
35,White,Male,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
36,White,Male,21,Private,197200,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
38,White,Male,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
39,White,Male,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
40,White,Male,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
41,White,Male,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
42,White,Male,24,Private,172987,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,White,Male,30,Private,188146,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,5013,0,40,United-States,<=50K
60,White,Male,30,Private,59496,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,2407,0,40,United-States,<=50K
61,White,Male,32,?,293936,7th-8th,4,Married-spouse-absent,?,Not-in-family,White,Male,0,0,40,?,<=50K
62,White,Male,48,Private,149640,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
63,White,Male,42,Private,116632,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
64,White,Male,29,Private,105598,Some-college,10,Divorced,Tech-support,Not-in-family,White,Male,0,0,58,United-States,<=50K
65,White,Male,36,Private,155537,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
68,White,Male,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
69,White,Male,25,?,200681,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
70,White,Male,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
72,White,Male,29,Self-emp-not-inc,162298,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,70,United-States,>50K
73,White,Male,23,Private,211678,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
74,White,Male,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
75,White,Male,27,Private,213921,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,40,Mexico,<=50K
76,White,Male,40,Private,32214,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
77,White,Male,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
79,White,Male,31,Local-gov,125927,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
80,White,Male,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
81,White,Male,52,Private,276515,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Cuba,<=50K
83,White,Male,59,Private,159937,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
86,White,Male,49,Local-gov,268234,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
87,White,Male,33,Private,202051,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
88,White,Male,30,Private,54334,9th,5,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
90,White,Male,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
94,White,Male,34,Local-gov,226296,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
95,White,Male,29,Local-gov,115585,Some-college,10,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,<=50K
96,White,Male,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
97,White,Male,37,Private,202683,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,>50K
99,Black,Male,32,Federal-gov,249409,HS-grad,9,Never-married,Other-service,Own-child,Black,Male,0,0,40,United-States,<=50K
100,White,Male,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

 **slice区间只作用在一个level的索引，如果三个level都是取区间的话，就要用三次slice**
* 注意slice用的时候一定要排序

####  需求：请选取出sex是female，不管race的全部数据

In [58]:
df = pd.read_csv('Python学习/Python第二节课/adultTest.csv')

In [59]:
df.set_index(['race','sex'],inplace=True,drop=False)

In [61]:
df.loc[(slice(None),['Female']),:]

KeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (2), lexsort depth (0)'

报错的原因：使用slice未排序！！！

In [62]:
df.sort_index(inplace=True)

In [63]:
df.loc[(slice(None),['Female']),:]

                           age          workclass  fnlwgt      education  \
race               sex
Amer-Indian-Eskimo Female   35            Private  153790   Some-college
                   Female   60                  ?   24215           10th
                   Female   25            Private  267044   Some-college
                   Female   23                  ?   99399   Some-college
                   Female   31            Private   78602     Assoc-acdm
                   Female   39            Private   19914   Some-college
                   Female   19                  ?   33487   Some-college
                   Female   31          Local-gov  151726     Assoc-acdm
                   Female   63            Private   30602        7th-8th
                   Female   18            Private   40829           11th
                   Female   40          Local-gov   50442   Some-college
                   Female   29            Private  100405           10th
                   Female   31          Local-gov   50442   Some-college
                   Female   25          Local-gov   44216        HS-grad
                   Female   17            Private  130125           10th
                   Female   28          Local-gov   25864        HS-grad
                   Female   31            Private  395170      Assoc-voc
                   Female   38          State-gov   31352   Some-college
                   Female   27                  ?  129661      Assoc-voc
                   Female   40            Private   20109   Some-college
                   Female   60        Federal-gov   21876   Some-college
                   Female   55          State-gov   26290      Assoc-voc
                   Female   63                  ?  445168      Bachelors
                   Female   47            Private  184005        HS-grad
                   Female   19   Self-emp-not-inc   30800           10th
                   Female   21            Private  216070     Assoc-acdm
                   Female   37            Private  163199   Some-college
                   Female   33            Private  110998        HS-grad
                   Female   24            Private  336088        HS-grad
                   Female   41          State-gov   47170      Bachelors
...                        ...                ...     ...            ...
White              Female   66            Private  269665        HS-grad
                   Female   58       Self-emp-inc  181974      Doctorate
                   Female   50            Private  485710      Doctorate
                   Female   41        Federal-gov  160467        Masters
                   Female   52            Private  301229      Assoc-voc
                   Female   27            Private  155382   Some-college
                   Female   48            Private  268083   Some-college
                   Female   28            Private  113987        HS-grad
                   Female   24            Private  381895           11th
                   Female   34            Private  321709        HS-grad
                   Female   50            Private  208630        Masters
                   Female   32            Private  192965        HS-grad
                   Female   46            Private   42972        Masters
                   Female   30            Private  176175      Assoc-voc
                   Female   27            Private  177398        HS-grad
                   Female   26            Private  191648     Assoc-acdm
                   Female   81                  ?  120478      Assoc-voc
                   Female   31            Private  292592        HS-grad
                   Female   29            Private  125976        HS-grad
                   Female   35                  ?  320084      Bachelors
                   Female   37            Private  179137   Some-college
                   Female   34            Private  160216      Bachelors
                   Female   45          State-gov  252208        HS-grad
                   Female   45          Local-gov  119199     Assoc-acdm
                   Female   39          Local-gov  111499     Assoc-acdm
                   Female   37            Private  198216     Assoc-acdm
                   Female   43          State-gov  255835   Some-college
                   Female   27            Private  257302     Assoc-acdm
                   Female   58            Private  151910        HS-grad
                   Female   52       Self-emp-inc  287927        HS-grad

                           education-num          marital-status  \
race               sex
Amer-Indian-Eskimo Female             10           Never-married
                   Female              6                Divorced
                   Female             10           Never-married
                   Female             10           Never-married
                   Female             12                Divorced
                   Female             10                Divorced
                   Female             10           Never-married
                   Female             12           Never-married
                   Female              4   Married-spouse-absent
                   Female              7           Never-married
                   Female             10           Never-married
                   Female              6      Married-civ-spouse
                   Female             10           Never-married
                   Female              9                Divorced
                   Female              6           Never-married
                   Female              9           Never-married
                   Female             11      Married-civ-spouse
                   Female             10                Divorced
                   Female             11      Married-civ-spouse
                   Female             10                Divorced
                   Female             10                Divorced
                   Female             11                 Widowed
                   Female             13                 Widowed
                   Female              9                Divorced
                   Female              6   Married-spouse-absent
                   Female             12      Married-civ-spouse
                   Female             10                Divorced
                   Female              9           Never-married
                   Female              9                Divorced
                   Female             13      Married-civ-spouse
...                                  ...                     ...
White              Female              9                 Widowed
                   Female             16           Never-married
                   Female             16                Divorced
                   Female             14                Divorced
                   Female             11               Separated
                   Female             10           Never-married
                   Female             10                Divorced
                   Female              9      Married-civ-spouse
                   Female              7                Divorced
                   Female              9           Never-married
                   Female             14                Divorced
                   Female              9               Separated
                   Female             14      Married-civ-spouse
                   Female             11                Divorced
                   Female              9           Never-married
                   Female             12           Never-married
                   Female             11                Divorced
                   Female              9      Married-civ-spouse
                   Female              9               Separated
                   Female             13      Married-civ-spouse
                   Female             10                Divorced
                   Female             13           Never-married
                   Female              9               Separated
                   Female             12                Divorced
                   Female             12      Married-civ-spouse
                   Female             12                Divorced
                   Female             10                Divorced
                   Female             12      Married-civ-spouse
                   Female              9                 Widowed
                   Female              9      Married-civ-spouse

                                   occupation     relationship  \
race               sex
Amer-Indian-Eskimo Female               Sales    Not-in-family
                   Female                   ?    Not-in-family
                   Female        Adm-clerical    Not-in-family
                   Female                   ?        Unmarried
                   Female       Other-service        Unmarried
                   Female        Adm-clerical        Unmarried
                   Female                   ?   Other-relative
                   Female        Adm-clerical        Own-child
                   Female       Other-service        Unmarried
                   Female               Sales   Other-relative
                   Female        Adm-clerical        Unmarried
                   Female     Farming-fishing             Wife
                   Female     Exec-managerial        Own-child
                   Female        Adm-clerical    Not-in-family
                   Female       Other-service        Own-child
                   Female     Exec-managerial        Unmarried
                   Female       Other-service             Wife
                   Female     Protective-serv        Unmarried
                   Female                   ?             Wife
                   Female   Handlers-cleaners    Not-in-family
                   Female      Prof-specialty    Not-in-family
                   Female     Exec-managerial    Not-in-family
                   Female                   ?    Not-in-family
                   Female     Exec-managerial    Not-in-family
                   Female        Adm-clerical        Unmarried
                   Female        Adm-clerical             Wife
                   Female        Tech-support    Not-in-family
                   Female       Other-service   Other-relative
                   Female     Exec-managerial    Not-in-family
                   Female      Prof-specialty             Wife
...                                       ...              ...
White              Female     Exec-managerial    Not-in-family
                   Female      Prof-specialty    Not-in-family
                   Female      Prof-specialty    Not-in-family
                   Female      Prof-specialty        Unmarried
                   Female               Sales        Unmarried
                   Female       Other-service    Not-in-family
                   Female     Exec-managerial    Not-in-family
                   Female   Machine-op-inspct             Wife
                   Female   Machine-op-inspct        Unmarried
                   Female       Other-service    Not-in-family
                   Female               Sales    Not-in-family
                   Female               Sales    Not-in-family
                   Female      Prof-specialty             Wife
                   Female        Adm-clerical        Unmarried
                   Female       Other-service        Unmarried
                   Female   Machine-op-inspct   Other-relative
                   Female                   ?        Unmarried
                   Female   Machine-op-inspct             Wife
                   Female               Sales        Unmarried
                   Female                   ?             Wife
                   Female        Adm-clerical        Unmarried
                   Female     Exec-managerial    Not-in-family
                   Female        Adm-clerical        Own-child
                   Female      Prof-specialty        Unmarried
                   Female        Adm-clerical             Wife
                   Female        Tech-support    Not-in-family
                   Female        Adm-clerical   Other-relative
                   Female        Tech-support             Wife
                   Female        Adm-clerical        Unmarried
                   Female     Exec-managerial             Wife

                                         race     sex  capital-gain  \
race               sex
Amer-Indian-Eskimo Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female          2977
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female          1055
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female          3325
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
                   Female  Amer-Indian-Eskimo  Female             0
...                                       ...     ...           ...
White              Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female          1506
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female             0
                   Female               White  Female         15024

                           capital-loss  hours-per-week  native-country  \
race               sex
Amer-Indian-Eskimo Female             0              40   United-States
                   Female             0              10   United-States
                   Female             0              20   United-States
                   Female             0              25   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              25   United-States
                   Female             0              35   United-States
                   Female             0              40   United-States
                   Female             0              32   United-States
                   Female             0              35   United-States
                   Female             0              20   United-States
                   Female             0              35   United-States
                   Female             0              24          Mexico
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              84   United-States
                   Female             0              40   United-States
                   Female             0              38   United-States
                   Female             0              56   United-States
                   Female             0              45   United-States
                   Female             0              40   United-States
                   Female             0              46   United-States
                   Female             0              40   United-States
                   Female             0              36   United-States
                   Female             0              50   United-States
                   Female             0              48   United-States
...                                 ...             ...             ...
White              Female             0              25   United-States
                   Female             0              99               ?
                   Female             0              50   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              25   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              40   United-States
                   Female             0              28   United-States
                   Female             0              50   United-States
                   Female             0              45   United-States

#### xs 在特定的level上选取数据

####  需求：请选取出sex是female，不管race的全部数据

In [64]:
df.xs("Female",level = "sex")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
race,,,,,,,,,,,,,,,
Amer-Indian-Eskimo,35,Private,153790,Some-college,10,Never-married,Sales,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,60,?,24215,10th,6,Divorced,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,10,United-States,<=50K
Amer-Indian-Eskimo,25,Private,267044,Some-college,10,Never-married,Adm-clerical,Not-in-family,Amer-Indian-Eskimo,Female,0,0,20,United-States,<=50K
Amer-Indian-Eskimo,23,?,99399,Some-college,10,Never-married,?,Unmarried,Amer-Indian-Eskimo,Female,0,0,25,United-States,<=50K
Amer-Indian-Eskimo,31,Private,78602,Assoc-acdm,12,Divorced,Other-service,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,39,Private,19914,Some-college,10,Divorced,Adm-clerical,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,19,?,33487,Some-college,10,Never-married,?,Other-relative,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,31,Local-gov,151726,Assoc-acdm,12,Never-married,Adm-clerical,Own-child,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,63,Private,30602,7th-8th,4,Married-spouse-absent,Other-service,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,18,Private,40829,11th,7,Never-married,Sales,Other-relative,Amer-Indian-Eskimo,Female,0,0,25,United-States,<=50K
Amer-Indian-Eskimo,40,Local-gov,50442,Some-college,10,Never-married,Adm-clerical,Unmarried,Amer-Indian-Eskimo,Female,2977,0,35,United-States,<=50K
Amer-Indian-Eskimo,29,Private,100405,10th,6,Married-civ-spouse,Farming-fishing,Wife,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,31,Local-gov,50442,Some-college,10,Never-married,Exec-managerial,Own-child,Amer-Indian-Eskimo,Female,0,0,32,United-States,<=50K
Amer-Indian-Eskimo,25,Local-gov,44216,HS-grad,9,Divorced,Adm-clerical,Not-in-family,Amer-Indian-Eskimo,Female,0,0,35,United-States,<=50K
Amer-Indian-Eskimo,17,Private,130125,10th,6,Never-married,Other-service,Own-child,Amer-Indian-Eskimo,Female,1055,0,20,United-States,<=50K
Amer-Indian-Eskimo,28,Local-gov,25864,HS-grad,9,Never-married,Exec-managerial,Unmarried,Amer-Indian-Eskimo,Female,0,0,35,United-States,<=50K
Amer-Indian-Eskimo,31,Private,395170,Assoc-voc,11,Married-civ-spouse,Other-service,Wife,Amer-Indian-Eskimo,Female,0,0,24,Mexico,<=50K
Amer-Indian-Eskimo,38,State-gov,31352,Some-college,10,Divorced,Protective-serv,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,>50K
Amer-Indian-Eskimo,27,?,129661,Assoc-voc,11,Married-civ-spouse,?,Wife,Amer-Indian-Eskimo,Female,0,0,40,United-States,>50K
Amer-Indian-Eskimo,40,Private,20109,Some-college,10,Divorced,Handlers-cleaners,Not-in-family,Amer-Indian-Eskimo,Female,0,0,84,United-States,<=50K
Amer-Indian-Eskimo,60,Federal-gov,21876,Some-college,10,Divorced,Prof-specialty,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,55,State-gov,26290,Assoc-voc,11,Widowed,Exec-managerial,Not-in-family,Amer-Indian-Eskimo,Female,0,0,38,United-States,<=50K
Amer-Indian-Eskimo,63,?,445168,Bachelors,13,Widowed,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,56,United-States,<=50K
Amer-Indian-Eskimo,47,Private,184005,HS-grad,9,Divorced,Exec-managerial,Not-in-family,Amer-Indian-Eskimo,Female,3325,0,45,United-States,<=50K
Amer-Indian-Eskimo,19,Self-emp-not-inc,30800,10th,6,Married-spouse-absent,Adm-clerical,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,21,Private,216070,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,Amer-Indian-Eskimo,Female,0,0,46,United-States,>50K
Amer-Indian-Eskimo,37,Private,163199,Some-college,10,Divorced,Tech-support,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,33,Private,110998,HS-grad,9,Never-married,Other-service,Other-relative,Amer-Indian-Eskimo,Female,0,0,36,United-States,<=50K
Amer-Indian-Eskimo,24,Private,336088,HS-grad,9,Divorced,Exec-managerial,Not-in-family,Amer-Indian-Eskimo,Female,0,0,50,United-States,<=50K
Amer-Indian-Eskimo,41,State-gov,47170,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Amer-Indian-Eskimo,Female,0,0,48,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
White,66,Private,269665,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,0,25,United-States,<=50K
White,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
White,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
White,41,Federal-gov,160467,Masters,14,Divorced,Prof-specialty,Unmarried,White,Female,1506,0,40,United-States,<=50K
White,52,Private,301229,Assoc-voc,11,Separated,Sales,Unmarried,White,Female,0,0,40,United-States,<=50K
White,27,Private,155382,Some-college,10,Never-married,Other-service,Not-in-family,White,Female,0,0,25,United-States,<=50K
White,48,Private,268083,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
White,28,Private,113987,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
White,24,Private,381895,11th,7,Divorced,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
White,34,Private,321709,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,28,United-States,<=50K
White,50,Private,208630,Masters,14,Divorced,Sales,Not-in-family,White,Female,0,0,50,United-States,>50K
White,32,Private,192965,HS-grad,9,Separated,Sales,Not-in-family,White,Female,0,0,45,United-States,<=50K
White,46,Private,42972,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,22,United-States,>50K
White,30,Private,176175,Assoc-voc,11,Divorced,Adm-clerical,Unmarried,White,Female,0,0,24,United-States,<=50K
White,27,Private,177398,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,64,United-States,<=50K
White,26,Private,191648,Assoc-acdm,12,Never-married,Machine-op-inspct,Other-relative,White,Female,0,0,15,United-States,<=50K
White,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K
White,31,Private,292592,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
White,29,Private,125976,HS-grad,9,Separated,Sales,Unmarried,White,Female,0,0,35,United-States,<=50K
White,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
White,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
White,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
White,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
White,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
White,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
White,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
White,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
White,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
White,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
White,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [66]:
df.xs("Female",level = 1).head()  #level =1 这里的1是位置

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
race,,,,,,,,,,,,,,,
Amer-Indian-Eskimo,35,Private,153790,Some-college,10,Never-married,Sales,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
Amer-Indian-Eskimo,60,?,24215,10th,6,Divorced,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,10,United-States,<=50K
Amer-Indian-Eskimo,25,Private,267044,Some-college,10,Never-married,Adm-clerical,Not-in-family,Amer-Indian-Eskimo,Female,0,0,20,United-States,<=50K
Amer-Indian-Eskimo,23,?,99399,Some-college,10,Never-married,?,Unmarried,Amer-Indian-Eskimo,Female,0,0,25,United-States,<=50K
Amer-Indian-Eskimo,31,Private,78602,Assoc-acdm,12,Divorced,Other-service,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K

#### 上面两张表得到的结果是一样的，总结为，dataframe里的索引不仅可以用名称，亦可以用位置。

#### 需求：选取出black,male的全部数据。

In [67]:
df.xs(("Black","Male"),level=("race","sex"))

            age          workclass  fnlwgt      education  education-num  \
race  sex
Black Male   53            Private  234721           11th              7
      Male   37            Private  280464   Some-college             10
      Male   32            Private  205019     Assoc-acdm             12
      Male   35        Federal-gov   76845            9th              5
      Male   20            Private  266015   Some-college             10
      Male   22          State-gov  311512   Some-college             10
      Male   57        Federal-gov  337895      Bachelors             13
      Male   32        Federal-gov  249409        HS-grad              9
      Male   49          Local-gov  197371      Assoc-voc             11
      Male   30            Private   77143      Bachelors             13
      Male   19            Private  301606   Some-college             10
      Male   71   Self-emp-not-inc  494223   Some-college             10
      Male   42            Private  228456      Bachelors             13
      Male   21            Private  312956        HS-grad              9
      Male   34            Private  483777        HS-grad              9
      Male   44          Local-gov  181344   Some-college             10
      Male   30            Private  633742   Some-college             10
      Male   34            Private  304030        HS-grad              9
      Male   41          Local-gov  523910      Bachelors             13
      Male   36            Private  128757      Bachelors             13
      Male   44          Local-gov  160943        HS-grad              9
      Male   37            Private  635913      Bachelors             13
      Male   90            Private   51744        HS-grad              9
      Male   54            Private  176681        HS-grad              9
      Male   35            Private  538583           11th              7
      Male   43            Private  477983        HS-grad              9
      Male   41            Private  206565   Some-college             10
      Male   19            Private  104112        HS-grad              9
      Male   45            Private  261192        HS-grad              9
      Male   45            Private  256649        HS-grad              9
...         ...                ...     ...            ...            ...
      Male   32            Private  124187            9th              5
      Male   27            Private  215873        HS-grad              9
      Male   22        Federal-gov   57216   Some-college             10
      Male   30       Self-emp-inc  178383   Some-college             10
      Male   25            Private  237065   Some-college             10
      Male   42       Self-emp-inc  161532      Bachelors             13
      Male   21            Private  213015        HS-grad              9
      Male   34            Private  331126        HS-grad              9
      Male   26            Private  385278        HS-grad              9
      Male   44            Private  118536            9th              5
      Male   56            Private  134153           10th              6
      Male   23          Local-gov  203078   Some-college             10
      Male   34            Private   90415      Assoc-voc             11
      Male   24            Private  206008     Assoc-acdm             12
      Male   21            Private   67804            9th              5
      Male   26            Private  156805   Some-college             10
      Male   46            Private  139514      Preschool              1
      Male   62            Private  271431            9th              5
      Male   61            Private  149620   Some-college             10
      Male   25            Private  390657   Some-college             10
      Male   38            Private  257416            9th              5
      Male   49                  ?  114648           12th              8
      Male   61            Private  355645        HS-grad              9
      Male   60                  ?  134152            9th              5
      Male   25            Private  403788        HS-grad              9
      Male   33            Private  182401           10th              6
      Male   40            Private  142657      Assoc-voc             11
      Male   33            Private  273243        HS-grad              9
      Male   22            Private  325033           12th              8
      Male   30            Private  345898        HS-grad              9

                 marital-status          occupation     relationship   race  \
race  sex
Black Male   Married-civ-spouse   Handlers-cleaners          Husband  Black
      Male   Married-civ-spouse     Exec-managerial          Husband  Black
      Male        Never-married               Sales    Not-in-family  Black
      Male   Married-civ-spouse     Farming-fishing          Husband  Black
      Male        Never-married               Sales        Own-child  Black
      Male   Married-civ-spouse       Other-service          Husband  Black
      Male   Married-civ-spouse      Prof-specialty          Husband  Black
      Male        Never-married       Other-service        Own-child  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male        Never-married     Exec-managerial        Own-child  Black
      Male        Never-married       Other-service        Own-child  Black
      Male            Separated               Sales        Unmarried  Black
      Male            Separated       Other-service   Other-relative  Black
      Male        Never-married        Craft-repair        Own-child  Black
      Male        Never-married   Handlers-cleaners    Not-in-family  Black
      Male   Married-civ-spouse     Exec-managerial          Husband  Black
      Male        Never-married        Craft-repair    Not-in-family  Black
      Male   Married-civ-spouse        Adm-clerical          Husband  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male   Married-civ-spouse       Other-service          Husband  Black
      Male   Married-civ-spouse    Transport-moving          Husband  Black
      Male        Never-married     Exec-managerial    Not-in-family  Black
      Male        Never-married       Other-service    Not-in-family  Black
      Male   Married-civ-spouse        Adm-clerical          Husband  Black
      Male            Separated    Transport-moving    Not-in-family  Black
      Male   Married-civ-spouse   Handlers-cleaners          Husband  Black
      Male        Never-married        Craft-repair    Not-in-family  Black
      Male        Never-married               Sales        Unmarried  Black
      Male   Married-civ-spouse       Other-service          Husband  Black
      Male   Married-civ-spouse   Machine-op-inspct          Husband  Black
...                         ...                 ...              ...    ...
      Male   Married-civ-spouse     Farming-fishing          Husband  Black
      Male        Never-married   Machine-op-inspct        Own-child  Black
      Male        Never-married        Adm-clerical        Own-child  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male             Divorced       Other-service        Own-child  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male        Never-married   Handlers-cleaners   Other-relative  Black
      Male        Never-married       Other-service        Unmarried  Black
      Male   Married-civ-spouse     Exec-managerial          Husband  Black
      Male   Married-civ-spouse   Machine-op-inspct          Husband  Black
      Male   Married-civ-spouse        Adm-clerical          Husband  Black
      Male   Married-civ-spouse     Protective-serv          Husband  Black
      Male        Never-married        Tech-support    Not-in-family  Black
      Male        Never-married      Prof-specialty        Own-child  Black
      Male        Never-married   Machine-op-inspct        Own-child  Black
      Male   Married-civ-spouse   Machine-op-inspct          Husband  Black
      Male   Married-civ-spouse   Machine-op-inspct   Other-relative  Black
      Male   Married-civ-spouse       Other-service          Husband  Black
      Male             Divorced       Other-service    Not-in-family  Black
      Male        Never-married       Other-service    Not-in-family  Black
      Male   Married-civ-spouse    Transport-moving          Husband  Black
      Male             Divorced                   ?   Other-relative  Black
      Male   Married-civ-spouse               Sales          Husband  Black
      Male             Divorced                   ?    Not-in-family  Black
      Male        Never-married        Craft-repair   Other-relative  Black
      Male        Never-married        Adm-clerical    Not-in-family  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male   Married-civ-spouse        Craft-repair          Husband  Black
      Male        Never-married     Protective-serv        Own-child  Black
      Male        Never-married        Craft-repair    Not-in-family  Black

             sex  capital-gain  capital-loss  hours-per-week  \
race  sex
Black Male  Male             0             0              40
      Male  Male             0             0              80
      Male  Male             0             0              50
      Male  Male             0             0              40
      Male  Male             0             0              44
      Male  Male             0             0              15
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              35
      Male  Male             0          1816               2
      Male  Male             0             0              50
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              38
      Male  Male             0             0              45
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male          7298             0              36
      Male  Male             0             0              40
      Male  Male             0             0              60
      Male  Male             0          2206              40
      Male  Male             0             0              20
      Male  Male          3674             0              40
      Male  Male             0             0              40
      Male  Male             0             0              45
      Male  Male             0             0              30
      Male  Male             0             0              40
      Male  Male             0             0              40
...          ...           ...           ...             ...
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              20
      Male  Male             0             0              70
      Male  Male             0             0              38
      Male  Male             0             0              60
      Male  Male          2176             0              40
      Male  Male             0             0              30
      Male  Male             0             0              60
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              20
      Male  Male             0             0              20
      Male  Male             0             0              40
      Male  Male             0             0              75
      Male  Male             0             0              42
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              35
      Male  Male             0             0              40
      Male  Male             0             0              40
      Male  Male             0             0              45
      Male  Male             0             0              40
      Male  Male             0             0              35
      Male  Male             0             0              46

                 native-country   class
race  sex
Black Male        United-States   <=50K
      Male        United-States    >50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States    >50K
      Male        United-States   <=50K
      Male        United-States    >50K
      Male              Germany   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States    >50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States    >50K
      Male        United-States   <=50K
      Male        United-States    >50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male                Haiti   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
...                         ...     ...
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male   Dominican-Republic   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K
      Male        United-States   <=50K

[1569 rows x 15 columns]

### ix 从DataFrame中选取行和列的子集

In [1]:
from pandas import DataFrame

In [4]:
data = DataFrame(np.arange(16).reshape((4,4)),index=["Ohio",'Colorado','Utah','New York'],
                columns=['one','two','three','four'])

In [5]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
#取数据框的第二行
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [8]:
data.ix[[2]]  #表格格式的返回

      one  two  three  four
Utah    8    9     10    11

In [12]:
#取数据框的第二列
data.ix[:,["two"]]

          two
Ohio        1
Colorado    5
Utah        9
New York   13

In [13]:
#取数据框的某两列
data.ix[:,[0,1]]   # [0,1]这里的0和1是表示位置

          one  two
Ohio        0    1
Colorado    4    5
Utah        8    9
New York   12   13

In [14]:
data.ix[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [15]:
data.ix[data.three > 5, :3]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [72]:
help(pd.IndexSlice) 
#You can use pd.IndexSlice to have a more natural syntax using : rather than using slice(None)

Help on _IndexSlice in module pandas.core.indexing object:

class _IndexSlice(builtins.object)
 |  # the public IndexSlicerMaker
 |
 |  Methods defined here:
 |
 |  __getitem__(self, arg)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [75]:
 idx = pd.IndexSlice

In [77]:
df.loc[idx[:,["Male"]],:] # 使用这个idxslice使用前也要排序！idxslice也是slice的一种。

                         age          workclass  fnlwgt      education  \
race               sex
Amer-Indian-Eskimo Male   34            Private  245487        7th-8th
                   Male   51            Private   56915        HS-grad
                   Male   20            Private   27337        HS-grad
                   Male   29            Private  182521        HS-grad
                   Male   27                  ?   90270     Assoc-acdm
                   Male   48   Self-emp-not-inc  243631   Some-college
                   Male   46            Private  134727           11th
                   Male   40            Private  100584           10th
                   Male   27            Private   23940        HS-grad
                   Male   53            Private  121618        7th-8th
                   Male   20            Private  137651   Some-college
                   Male   31            Private  100997   Some-college
                   Male   52   Self-emp-not-inc  242341        7th-8th
                   Male   56        Federal-gov  162137        HS-grad
                   Male   42            Private  245626        HS-grad
                   Male   51            Private  209912      Bachelors
                   Male   35            Private   25955           11th
                   Male   31            Private  197023      Assoc-voc
                   Male   28            Private  259351           10th
                   Male   44            Private  100584        HS-grad
                   Male   41            Private  113555   Some-college
                   Male   45   Self-emp-not-inc  239093   Some-college
                   Male   20                  ?   34862   Some-college
                   Male   28            Private   25955      Assoc-voc
                   Male   43            Private  161226      Bachelors
                   Male   29            Private  120986        HS-grad
                   Male   41            Private  147314        HS-grad
                   Male   45            Private   26781        HS-grad
                   Male   42            Private  108506        HS-grad
                   Male   33            Private  163392        HS-grad
...                      ...                ...     ...            ...
White              Male   26            Private  179010   Some-college
                   Male   18            Private  436163           11th
                   Male   57            Private  153918        HS-grad
                   Male   34            Private   60567           11th
                   Male   71            Private  138145            9th
                   Male   35          Local-gov   79649      Bachelors
                   Male   47            Private  312088        HS-grad
                   Male   38            Private   32916      Assoc-voc
                   Male   50            Private  302372      Bachelors
                   Male   39            Private  107302        HS-grad
                   Male   20            Private  270436        HS-grad
                   Male   66        Federal-gov   47358           10th
                   Male   36            Private  131459        7th-8th
                   Male   57          Local-gov  110417        HS-grad
                   Male   46            Private  364548   Some-college
                   Male   58            Private  147707           11th
                   Male   30            Private   77266        HS-grad
                   Male   32            Private  211349           10th
                   Male   22            Private  203715   Some-college
                   Male   34            Private  204461      Doctorate
                   Male   71                  ?  287372      Doctorate
                   Male   72                  ?  129912        HS-grad
                   Male   43            Private  260761        HS-grad
                   Male   65   Self-emp-not-inc   99359    Prof-school
                   Male   43   Self-emp-not-inc   27242   Some-college
                   Male   43            Private   84661      Assoc-voc
                   Male   53            Private  321865        Masters
                   Male   22            Private  310152   Some-college
                   Male   40            Private  154374        HS-grad
                   Male   22            Private  201490        HS-grad

                         education-num       marital-status  \
race               sex
Amer-Indian-Eskimo Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9        Never-married
                   Male              9        Never-married
                   Male             12   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male              7             Divorced
                   Male              6             Divorced
                   Male              9        Never-married
                   Male              4        Never-married
                   Male             10        Never-married
                   Male             10   Married-civ-spouse
                   Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             13             Divorced
                   Male              7        Never-married
                   Male             11   Married-civ-spouse
                   Male              6        Never-married
                   Male              9   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male             10        Never-married
                   Male             11             Divorced
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
...                                ...                  ...
White              Male             10        Never-married
                   Male              7        Never-married
                   Male              9   Married-civ-spouse
                   Male              7             Divorced
                   Male              5   Married-civ-spouse
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             11   Married-civ-spouse
                   Male             13   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9        Never-married
                   Male              6   Married-civ-spouse
                   Male              4   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             10   Married-civ-spouse
                   Male              7   Married-civ-spouse
                   Male              9             Divorced
                   Male              6   Married-civ-spouse
                   Male             10        Never-married
                   Male             16   Married-civ-spouse
                   Male             16   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male              9   Married-civ-spouse
                   Male             15        Never-married
                   Male             10   Married-civ-spouse
                   Male             11   Married-civ-spouse
                   Male             14   Married-civ-spouse
                   Male             10        Never-married
                   Male              9   Married-civ-spouse
                   Male              9        Never-married

                                 occupation     relationship  \
race               sex
Amer-Indian-Eskimo Male    Transport-moving          Husband
                   Male        Craft-repair          Husband
                   Male   Handlers-cleaners        Own-child
                   Male        Craft-repair    Not-in-family
                   Male                   ?        Own-child
                   Male        Craft-repair          Husband
                   Male   Machine-op-inspct        Unmarried
                   Male        Craft-repair    Not-in-family
                   Male   Handlers-cleaners   Other-relative
                   Male    Transport-moving    Not-in-family
                   Male   Machine-op-inspct        Own-child
                   Male      Prof-specialty          Husband
                   Male        Craft-repair          Husband
                   Male    Transport-moving          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial    Not-in-family
                   Male       Other-service        Unmarried
                   Male   Machine-op-inspct          Husband
                   Male       Other-service   Other-relative
                   Male   Machine-op-inspct          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial          Husband
                   Male                   ?        Own-child
                   Male        Craft-repair    Not-in-family
                   Male   Machine-op-inspct          Husband
                   Male    Transport-moving          Husband
                   Male               Sales          Husband
                   Male      Prof-specialty          Husband
                   Male    Transport-moving          Husband
                   Male      Prof-specialty          Husband
...                                     ...              ...
White              Male        Craft-repair    Not-in-family
                   Male      Prof-specialty        Own-child
                   Male    Transport-moving          Husband
                   Male    Transport-moving        Unmarried
                   Male       Other-service          Husband
                   Male      Prof-specialty          Husband
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male      Prof-specialty          Husband
                   Male      Prof-specialty          Husband
                   Male   Machine-op-inspct        Own-child
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male        Craft-repair          Husband
                   Male     Exec-managerial          Husband
                   Male               Sales          Husband
                   Male    Transport-moving    Not-in-family
                   Male    Transport-moving          Husband
                   Male        Adm-clerical        Own-child
                   Male      Prof-specialty          Husband
                   Male                   ?          Husband
                   Male                   ?          Husband
                   Male   Machine-op-inspct          Husband
                   Male      Prof-specialty    Not-in-family
                   Male        Craft-repair          Husband
                   Male               Sales          Husband
                   Male     Exec-managerial          Husband
                   Male     Protective-serv    Not-in-family
                   Male   Machine-op-inspct          Husband
                   Male        Adm-clerical        Own-child

                                       race   sex  capital-gain  capital-loss  \
race               sex
Amer-Indian-Eskimo Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male          7688             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male          7298             0
                   Male  Amer-Indian-Eskimo  Male          3137             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
                   Male  Amer-Indian-Eskimo  Male             0             0
...                                     ...   ...           ...           ...
White              Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0           880
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male          3471             0
                   Male               White  Male             0             0
                   Male               White  Male         99999             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male          1086             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0
                   Male               White  Male             0             0

                         hours-per-week  native-country   class
race               sex
Amer-Indian-Eskimo Male              45          Mexico   <=50K
                   Male              40   United-States   <=50K
                   Male              48   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States    >50K
                   Male              43         Germany   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40          Mexico   <=50K
                   Male              40   United-States   <=50K
                   Male              50   United-States    >50K
                   Male              40   United-States   <=50K
                   Male              72   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              65   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male               8   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              48   United-States    >50K
...                                 ...             ...     ...
White              Male              65   United-States   <=50K
                   Male              20   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              60   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              50   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              55   United-States    >50K
                   Male              40   United-States   <=50K
                   Male              45               ?    >50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States   <=50K
                   Male              40   United-States    >50K
                   Male              48   United-States    >50K
                   Male              40   United-States   <=50K

# Group - by  分组计算
plit – apply – combine                         
split: 很具某些条件对数据进行分组                          
apply:对每一个group独立的应用函数  #重点是先分组 再应用函数                    
combine：将结果数据组合到某种数据结构中

**重点： Apply               
aggregation: 对每一个小组做一些统计上的计算              
transformation: 对group做一些特别的计算                 
filtration:对group进行某些条件的过滤  **

### split

In [78]:
df = pd.read_csv('Python学习/Python第二节课/adultTest.csv')

In [79]:
help(df.groupby)

Help on method groupby in module pandas.core.generic:

groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Group series using mapper (dict or key function, apply given function
    to group, return result as series) or by a series of columns.

    Parameters
    ----------
    by : mapping function / list of functions, dict, Series, or tuple /
        list of column names.
        Called on each element of the object index to determine the groups.
        If a dict or Series is passed, the Series or dict VALUES will be
        used to determine the groups
    axis : int, default 0
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierarchical), group by a particular
        level or levels
    as_index : boolean, default True
        For aggregated output, return object with group labels as the
        index. Only relevant for DataFrame input. as_index=False is
        effectively "SQL-style" grouped output
    sort : boolean, default True
        Sort group keys. Get better performance by turning this off.
        Note this does not influence the order of observations within each
        group.  groupby preserves the order of rows within each group.
    group_keys : boolean, default True
        When calling apply, add group keys to index to identify pieces
    squeeze : boolean, default False
        reduce the dimensionality of the return type if possible,
        otherwise return a consistent type

    Examples
    --------
    DataFrame results

    >>> data.groupby(func, axis=0).mean()
    >>> data.groupby(['col1', 'col2'])['col3'].mean()

    DataFrame with hierarchical index

    >>> data.groupby(['col1', 'col2']).mean()

    Returns
    -------
    GroupBy object

In [80]:
#被race分组
grouped= df.groupby('race')

In [81]:
grouped

In [88]:
grouped.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
50,25,Private,32275,Some-college,10,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0,0,40,United-States,<=50K
93,30,Private,117747,HS-grad,9,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,1573,35,?,<=50K
139,49,Private,81973,Some-college,10,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>50K
212,35,Private,153790,Some-college,10,Never-married,Sales,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
226,60,?,24215,10th,6,Divorced,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,10,United-States,<=50K
233,33,Private,110978,Some-college,10,Divorced,Craft-repair,Other-relative,Other,Female,0,0,40,United-States,<=50K
356,65,Private,161400,11th,7,Widowed,Other-service,Unmarried,Other,Male,0,0,40,United-States,<=50K
404,28,Private,166481,7th-8th,4,Married-civ-spouse,Handlers-cleaners,Husband,Other,Male,0,2179,40,Puerto-Rico,<=50K
447,51,Private,56915,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
516,25,Private,267044,Some-college,10,Never-married,Adm-clerical,Not-in-family,Amer-Indian-Eskimo,Female,0,0,20,United-States,<=50K
530,44,Private,109339,11th,7,Divorced,Machine-op-inspct,Unmarried,Other,Female,0,0,46,Puerto-Rico,<=50K

In [154]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

上下两张表对照的看，可以发现，groupby分组后返回的表还是原数据集的表，但是在对原数据集进行函数计算的时候就开始分组计算了。

In [82]:
grouped.age

In [83]:
grouped.mean()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
race,,,,,,
Amer-Indian-Eskimo,37.173633,120831.147910,9.311897,625.266881,34.176849,40.048232
Asian-Pac-Islander,37.746872,159940.609240,10.960539,1478.358037,97.222329,40.127045
Black,37.767926,228013.124200,9.486236,609.940461,60.385083,38.422855
Other,33.457565,197124.191882,8.841328,934.660517,61.070111,39.468635
White,38.769881,187298.064280,10.135246,1121.660375,90.806155,40.689100

In [84]:
grouped.sum()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
race,,,,,,
Amer-Indian-Eskimo,11561,37578487,2896,194458,10629,12455
Asian-Pac-Islander,39219,166178293,11388,1536014,101014,41692
Black,117987,712313000,29635,1905454,188643,120033
Other,9067,53420656,2396,253293,16550,10696
White,1078423,5209882956,281922,31200105,2525864,1131808

In [86]:
grouped.median()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
race,,,,,,
Amer-Indian-Eskimo,35,102541,9,0,0,40
Asian-Pac-Islander,36,143098,10,0,0,40
Black,36,205934,9,0,0,40
Other,31,188793,9,0,0,40
White,37,177627,10,0,0,40

In [87]:
grouped["age"].mean()

race
Amer-Indian-Eskimo    37.173633
Asian-Pac-Islander    37.746872
Black                 37.767926
Other                 33.457565
White                 38.769881
Name: age, dtype: float64

In [89]:
grouped["age","fnlwgt"].mean()

                          age         fnlwgt
race
Amer-Indian-Eskimo  37.173633  120831.147910
Asian-Pac-Islander  37.746872  159940.609240
Black               37.767926  228013.124200
Other               33.457565  197124.191882
White               38.769881  187298.064280

In [90]:
grouped.size()

race
Amer-Indian-Eskimo      311
Asian-Pac-Islander     1039
Black                  3124
Other                   271
White                 27816
dtype: int64

In [92]:
grouped.groups  # 下面的出来的数据是索引名

{'Amer-Indian-Eskimo': [15,
  212,
  226,
  447,
  516,
  565,
  596,
  607,
  903,
  940,
  1216,
  1425,
  1464,
  1494,
  1715,
  1844,
  2036,
  2313,
  2383,
  2401,
  2445,
  2488,
  2601,
  2610,
  2622,
  2718,
  2720,
  2798,
  2993,
  3406,
  3443,
  3589,
  3598,
  3605,
  3676,
  3707,
  3729,
  3821,
  3838,
  3843,
  4049,
  4112,
  4169,
  4287,
  4348,
  4426,
  4611,
  4666,
  4948,
  5022,
  5127,
  5214,
  5358,
  5420,
  5464,
  5466,
  5481,
  5624,
  5775,
  5846,
  5878,
  6049,
  6184,
  6228,
  6391,
  6467,
  6504,
  6582,
  6627,
  6752,
  6902,
  6930,
  6966,
  7042,
  7078,
  7161,
  7375,
  7519,
  7521,
  7656,
  7686,
  8089,
  8149,
  8155,
  8288,
  8330,
  8670,
  8834,
  8856,
  8866,
  9196,
  9226,
  9266,
  9634,
  9694,
  9697,
  9825,
  9847,
  9965,
  10012,
  10033,
  10152,
  10269,
  10340,
  10712,
  10828,
  10983,
  11163,
  11263,
  11546,
  11802,
  11854,
  12220,
  12275,
  12492,
  12553,
  12845,
  12870,
  13271,
  13323,
  13828,
  13932,
  13986,
  14112,
  14151,
  14177,
  14360,
  14363,
  14442,
  14720,
  14732,
  14775,
  14810,
  14899,
  14924,
  14945,
  15131,
  15212,
  15276,
  15527,
  15674,
  15820,
  15907,
  16178,
  16183,
  16197,
  16213,
  16423,
  16505,
  16847,
  16934,
  17059,
  17096,
  17134,
  17191,
  17379,
  17386,
  17398,
  17581,
  17589,
  17733,
  17748,
  17781,
  17798,
  17849,
  17994,
  18189,
  18298,
  18429,
  18442,
  18505,
  18534,
  18691,
  18697,
  18769,
  18783,
  18790,
  18988,
  19073,
  19089,
  19137,
  19203,
  19230,
  19279,
  19443,
  19484,
  19515,
  19564,
  19572,
  19580,
  19740,
  19744,
  19759,
  19839,
  20015,
  20091,
  20097,
  20351,
  20462,
  20472,
  20517,
  20799,
  20991,
  21112,
  21340,
  21396,
  21410,
  21421,
  21438,
  21555,
  21685,
  21688,
  22035,
  22059,
  22087,
  22188,
  22244,
  22299,
  22417,
  22477,
  22583,
  22618,
  22735,
  22779,
  22896,
  22902,
  23122,
  23227,
  23237,
  23238,
  23291,
  23724,
  24078,
  24143,
  24263,
  24326,
  24376,
  24402,
  24555,
  24691,
  24967,
  25016,
  25030,
  25047,
  25070,
  25125,
  25168,
  25195,
  25460,
  25647,
  25757,
  26043,
  26093,
  26156,
  26166,
  26173,
  26196,
  26243,
  26380,
  26425,
  26589,
  26901,
  27083,
  27207,
  27496,
  27623,
  27657,
  27767,
  27911,
  27977,
  28151,
  28248,
  28278,
  28297,
  28398,
  28648,
  28742,
  28785,
  28908,
  28973,
  29021,
  29133,
  29260,
  29403,
  29408,
  29537,
  29864,
  29990,
  30057,
  30115,
  30382,
  30579,
  30586,
  30591,
  30757,
  30775,
  30782,
  30864,
  30938,
  30968,
  30986,
  30997,
  31087,
  31358,
  31915,
  32008,
  32231,
  32242,
  32249,
  32425,
  32551],
 'Asian-Pac-Islander': [11,
  14,
  27,
  93,
  139,
  152,
  162,
  163,
  213,
  255,
  265,
  297,
  301,
  304,
  311,
  434,
  455,
  591,
  652,
  655,
  668,
  731,
  873,
  892,
  916,
  917,
  968,
  1029,
  1077,
  1092,
  1095,
  1119,
  1158,
  1179,
  1217,
  1255,
  1281,
  1327,
  1348,
  1368,
  1411,
  1415,
  1471,
  1478,
  1515,
  1581,
  1609,
  1622,
  1708,
  1717,
  1756,
  1787,
  1793,
  1803,
  1839,
  1864,
  1932,
  1969,
  1975,
  2003,
  2060,
  2068,
  2096,
  2104,
  2126,
  2130,
  2135,
  2208,
  2249,
  2259,
  2286,
  2303,
  2323,
  2330,
  2339,
  2412,
  2432,
  2509,
  2512,
  2526,
  2547,
  2558,
  2587,
  2590,
  2653,
  2654,
  2655,
  2834,
  2898,
  2926,
  2943,
  2989,
  3021,
  3064,
  3110,
  3148,
  3184,
  3199,
  3202,
  3239,
  3557,
  3579,
  3627,
  3636,
  3647,
  3657,
  3708,
  3714,
  3715,
  3753,
  3812,
  3832,
  3856,
  3879,
  3909,
  3987,
  3993,
  4006,
  4055,
  4059,
  4066,
  4108,
  4168,
  4197,
  4262,
  4303,
  4337,
  4367,
  4403,
  4409,
  4452,
  4480,
  4512,
  4523,
  4532,
  4538,
  4583,
  4596,
  4598,
  4610,
  4617,
  4625,
  4650,
  4724,
  4768,
  4779,
  4785,
  4786,
  4798,
  4803,
  4826,
  4854,
  4903,
  4919,
  4972,
  5012,
  5081,
  5104,
  5196,
  5219,
  5330,
  5395,
  5415,
  5424,
  5435,
  5448,
  5519,
  5525,
  5560,
  5592,
  5603,
  5617,
  5629,
  5698,
  5771,
  5786,
  5896,
  5903,
  5971,
  5980,
  6006,
  6032,
  6038,
  6065,
  6122,
  6125,
  6150,
  6175,
  6219,
  6269,
  6314,
  6321,
  6387,
  6493,
  6505,
  6549,
  6560,
  6570,
  6626,
  6631,
  6751,
  6853,
  6871,
  6918,
  6921,
  6929,
  6952,
  6964,
  7007,
  7016,
  7049,
  7057,
  7059,
  7060,
  7072,
  7202,
  7210,
  7258,
  7285,
  7310,
  7320,
  7325,
  7345,
  7435,
  7461,
  7469,
  7507,
  7529,
  7605,
  7606,
  7636,
  7669,
  7673,
  7697,
  7698,
  7800,
  7808,
  7829,
  7909,
  7932,
  7980,
  8014,
  8024,
  8059,
  8066,
  8070,
  8075,
  8112,
  8122,
  8152,
  8282,
  8356,
  8388,
  8414,
  8427,
  8478,
  8497,
  8508,
  8535,
  8572,
  8633,
  8688,
  8844,
  8845,
  8873,
  8874,
  8895,
  8896,
  8898,
  8953,
  8962,
  8992,
  8993,
  9017,
  9067,
  9128,
  9147,
  9215,
  9318,
  9353,
  9371,
  9404,
  9441,
  9457,
  9463,
  9470,
  9525,
  9533,
  9537,
  9550,
  9553,
  9568,
  9580,
  9626,
  9677,
  9678,
  9711,
  9735,
  9780,
  9811,
  9836,
  9848,
  9859,
  9860,
  9865,
  9911,
  9939,
  9952,
  9957,
  10026,
  10027,
  10091,
  10107,
  10188,
  10208,
  10218,
  10219,
  10233,
  10276,
  10296,
  10335,
  10341,
  10374,
  10378,
  10384,
  10399,
  10408,
  10480,
  10534,
  10571,
  10590,
  10630,
  10634,
  10661,
  10674,
  10724,
  10736,
  10762,
  10770,
  10772,
  10835,
  10984,
  11134,
  11188,
  11252,
  11253,
  11260,
  11271,
  11279,
  11284,
  11315,
  11316,
  11354,
  11384,
  11388,
  11401,
  11466,
  11483,
  11589,
  11597,
  11637,
  11747,
  11756,
  11764,
  11916,
  11946,
  11979,
  11986,
  12070,
  12071,
  12093,
  12129,
  12172,
  12221,
  12262,
  12282,
  12404,
  12406,
  12413,
  12438,
  12451,
  12464,
  12560,
  12563,
  12576,
  12584,
  12614,
  12625,
  12626,
  12672,
  12675,
  12676,
  12684,
  12725,
  12732,
  12779,
  12795,
  12865,
  12913,
  12917,
  12931,
  12973,
  12996,
  13031,
  13122,
  13139,
  13159,
  13161,
  13211,
  13213,
  13229,
  13244,
  13325,
  13327,
  13422,
  13430,
  13468,
  13476,
  13483,
  13546,
  13550,
  13551,
  13589,
  13641,
  13698,
  13706,
  13747,
  13768,
  13780,
  13785,
  13817,
  13821,
  13827,
  13843,
  13862,
  13890,
  13923,
  13933,
  13971,
  14041,
  14074,
  14118,
  14147,
  14159,
  14194,
  14214,
  14234,
  14242,
  14273,
  14290,
  14299,
  14318,
  14339,
  14368,
  14374,
  14401,
  14488,
  14507,
  14531,
  14557,
  14572,
  14582,
  14600,
  14672,
  14685,
  14704,
  14740,
  14752,
  14762,
  14816,
  14882,
  14908,
  14927,
  15005,
  15037,
  15043,
  15124,
  15177,
  15183,
  15197,
  15222,
  15310,
  15383,
  15403,
  15443,
  15466,
  15499,
  15643,
  15644,
  15692,
  15698,
  15762,
  15768,
  15868,
  15871,
  15877,
  15902,
  15967,
  15978,
  16006,
  16025,
  16068,
  16103,
  16150,
  16192,
  16326,
  16328,
  16336,
  16447,
  16494,
  16497,
  16528,
  16564,
  16569,
  16570,
  16576,
  16583,
  16620,
  16630,
  16655,
  16673,
  16729,
  16778,
  16843,
  16862,
  16923,
  16924,
  17025,
  17073,
  17110,
  17135,
  17142,
  17163,
  17172,
  17173,
  17207,
  17220,
  17259,
  17269,
  17300,
  17341,
  17382,
  17412,
  17447,
  17538,
  17540,
  17568,
  17595,
  17823,
  17834,
  17835,
  17877,
  17895,
  17947,
  17984,
  18010,
  18031,
  18055,
  18065,
  18075,
  18086,
  18096,
  18159,
  18160,
  18213,
  18238,
  18244,
  18248,
  18338,
  18369,
  18385,
  18412,
  18450,
  18459,
  18509,
  18531,
  18538,
  18556,
  18566,
  18569,
  18636,
  18657,
  18686,
  18717,
  18808,
  18813,
  18881,
  18889,
  18896,
  18906,
  18909,
  18968,
  19000,
  19027,
  19029,
  19035,
  19038,
  19046,
  19047,
  19094,
  19167,
  19170,
  19200,
  19273,
  19322,
  19337,
  19344,
  19351,
  19491,
  19501,
  19509,
  19511,
  19526,
  19538,
  19542,
  19561,
  19611,
  19612,
  19693,
  19725,
  19743,
  19750,
  19755,
  19926,
  19959,
  19962,
  19964,
  19989,
  20104,
  20137,
  20166,
  20172,
  20194,
  20229,
  20292,
  20360,
  20383,
  20417,
  20423,
  20465,
  20494,
  20499,
  20543,
  20553,
  20561,
  20621,
  20630,
  20692,
  20698,
  20709,
  20775,
  20780,
  20816,
  20825,
  20892,
  20905,
  20936,
  21048,
  21108,
  21128,
  21130,
  21158,
  21218,
  21348,
  21370,
  21441,
  21452,
  21503,
  21520,
  21611,
  21672,
  21705,
  21778,
  21781,
  21798,
  21846,
  21876,
  21911,
  21927,
  21949,
  21959,
  21975,
  21999,
  22021,
  22028,
  22029,
  22055,
  22076,
  22079,
  22106,
  22174,
  22197,
  22220,
  22225,
  22289,
  22307,
  22317,
  22324,
  22329,
  22405,
  22427,
  22429,
  22431,
  22446,
  22487,
  22564,
  22575,
  22652,
  22669,
  22696,
  22710,
  22790,
  22797,
  22876,
  22900,
  22956,
  23019,
  23021,
  23022,
  23177,
  23220,
  23236,
  23307,
  23351,
  23357,
  23449,
  23455,
  23458,
  23465,
  23474,
  23483,
  23508,
  23564,
  23590,
  23607,
  23647,
  23650,
  23689,
  23721,
  23735,
  23741,
  23804,
  23832,
  23840,
  23891,
  23902,
  23915,
  23917,
  23947,
  24006,
  24056,
  24070,
  24102,
  24156,
  24175,
  24178,
  24202,
  24213,
  24295,
  24330,
  24378,
  24408,
  24423,
  24483,
  24629,
  24634,
  24662,
  24693,
  24735,
  24818,
  24891,
  24940,
  24980,
  24981,
  24988,
  25002,
  25010,
  25101,
  25105,
  25118,
  25140,
  25153,
  25192,
  25227,
  25231,
  25238,
  25248,
  25258,
  25319,
  25350,
  25376,
  25421,
  25423,
  25463,
  25466,
  25561,
  25565,
  25577,
  25619,
  25636,
  25739,
  25743,
  25752,
  25756,
  25766,
  25816,
  25841,
  25850,
  25873,
  25897,
  25899,
  25946,
  25975,
  25990,
  25994,
  26007,
  26018,
  26091,
  26150,
  26152,
  26259,
  26305,
  26321,
  26356,
  26400,
  26432,
  26447,
  26457,
  26476,
  26494,
  26545,
  26568,
  26606,
  26649,
  26686,
  26688,
  26728,
  26754,
  26762,
  26777,
  26792,
  26862,
  26878,
  26879,
  26902,
  26904,
  26922,
  26972,
  27002,
  27007,
  27026,
  27033,
  27046,
  27056,
  27071,
  27135,
  27170,
  27214,
  27244,
  27246,
  27306,
  27315,
  27329,
  27338,
  27355,
  27374,
  27433,
  27480,
  27512,
  27525,
  27602,
  27642,
  27647,
  27659,
  27661,
  27670,
  27714,
  27799,
  27804,
  27808,
  27817,
  27820,
  27846,
  27867,
  27874,
  27904,
  27974,
  28002,
  28049,
  28088,
  28195,
  28245,
  28270,
  28295,
  28335,
  28433,
  28452,
  28484,
  28511,
  28557,
  28564,
  28581,
  28651,
  28659,
  28665,
  28693,
  28749,
  28773,
  28774,
  28781,
  28798,
  28800,
  28816,
  28835,
  28884,
  28915,
  28920,
  28922,
  28924,
  28925,
  28938,
  28942,
  28995,
  28997,
  29026,
  29029,
  29046,
  29104,
  29158,
  29207,
  29255,
  29290,
  29311,
  29343,
  29377,
  29393,
  29406,
  29488,
  29496,
  29516,
  29547,
  29552,
  29553,
  29554,
  29631,
  29633,
  29721,
  29728,
  29777,
  29786,
  29929,
  29936,
  29996,
  30135,
  30152,
  30200,
  30230,
  30289,
  30301,
  30325,
  30326,
  30338,
  30347,
  30455,
  30533,
  30584,
  30732,
  30735,
  30790,
  30833,
  30871,
  30925,
  30974,
  30975,
  30980,
  30989,
  31002,
  31003,
  31047,
  31060,
  31061,
  31079,
  31132,
  31181,
  31185,
  31243,
  31272,
  31282,
  31292,
  31302,
  31327,
  31332,
  31357,
  31377,
  31418,
  31425,
  31429,
  31491,
  31506,
  31511,
  ...],
 'Black': [3,
  4,
  6,
  10,
  13,
  21,
  22,
  31,
  34,
  45,
  71,
  92,
  99,
  117,
  122,
  124,
  134,
  145,
  157,
  159,
  176,
  177,
  180,
  182,
  185,
  190,
  192,
  206,
  210,
  215,
  222,
  223,
  230,
  231,
  251,
  252,
  275,
  282,
  294,
  312,
  313,
  326,
  330,
  338,
  339,
  344,
  373,
  374,
  410,
  411,
  418,
  436,
  446,
  450,
  453,
  457,
  461,
  484,
  485,
  505,
  508,
  511,
  522,
  532,
  536,
  539,
  553,
  554,
  563,
  605,
  608,
  616,
  621,
  622,
  625,
  630,
  631,
  633,
  660,
  667,
  683,
  691,
  706,
  707,
  711,
  715,
  734,
  736,
  738,
  747,
  748,
  759,
  785,
  795,
  797,
  801,
  811,
  874,
  876,
  888,
  890,
  907,
  914,
  923,
  941,
  945,
  952,
  978,
  982,
  986,
  1006,
  1024,
  1026,
  1033,
  1038,
  1041,
  1076,
  1103,
  1124,
  1127,
  1130,
  1137,
  1165,
  1171,
  1186,
  1195,
  1200,
  1204,
  1234,
  1270,
  1273,
  1283,
  1293,
  1298,
  1300,
  1301,
  1328,
  1329,
  1332,
  1354,
  1356,
  1366,
  1367,
  1370,
  1375,
  1386,
  1391,
  1393,
  1394,
  1396,
  1404,
  1417,
  1421,
  1424,
  1427,
  1434,
  1451,
  1454,
  1455,
  1458,
  1461,
  1465,
  1484,
  1508,
  1509,
  1510,
  1519,
  1525,
  1530,
  1533,
  1539,
  1555,
  1559,
  1564,
  1565,
  1567,
  1570,
  1597,
  1603,
  1606,
  1629,
  1640,
  1646,
  1649,
  1654,
  1664,
  1686,
  1695,
  1700,
  1714,
  1731,
  1732,
  1754,
  1763,
  1766,
  1774,
  1794,
  1797,
  1801,
  1813,
  1815,
  1827,
  1845,
  1852,
  1854,
  1865,
  1871,
  1875,
  1883,
  1917,
  1921,
  1931,
  1936,
  1942,
  1947,
  1952,
  1967,
  1971,
  1979,
  1982,
  1989,
  2005,
  2006,
  2033,
  2034,
  2041,
  2052,
  2073,
  2075,
  2080,
  2107,
  2122,
  2128,
  2150,
  2156,
  2165,
  2169,
  2192,
  2205,
  2207,
  2209,
  2218,
  2223,
  2228,
  2232,
  2255,
  2267,
  2288,
  2343,
  2349,
  2364,
  2365,
  2375,
  2376,
  2400,
  2435,
  2437,
  2441,
  2448,
  2463,
  2469,
  2486,
  2499,
  2510,
  2515,
  2518,
  2533,
  2539,
  2541,
  2561,
  2564,
  2575,
  2578,
  2593,
  2596,
  2611,
  2615,
  2650,
  2661,
  2685,
  2730,
  2742,
  2745,
  2758,
  2773,
  2775,
  2782,
  2784,
  2795,
  2801,
  2807,
  2811,
  2824,
  2841,
  2842,
  2847,
  2855,
  2869,
  2875,
  2882,
  2884,
  2906,
  2922,
  2927,
  2936,
  2938,
  2940,
  2945,
  2951,
  2953,
  2954,
  2961,
  2974,
  2975,
  2979,
  2986,
  3019,
  3023,
  3040,
  3069,
  3072,
  3073,
  3086,
  3096,
  3131,
  3143,
  3158,
  3161,
  3179,
  3188,
  3191,
  3193,
  3194,
  3223,
  3228,
  3230,
  3234,
  3241,
  3251,
  3268,
  3269,
  3298,
  3308,
  3314,
  3316,
  3334,
  3338,
  3345,
  3362,
  3376,
  3384,
  3397,
  3399,
  3402,
  3409,
  3411,
  3442,
  3454,
  3477,
  3484,
  3486,
  3495,
  3496,
  3526,
  3529,
  3535,
  3546,
  3548,
  3551,
  3559,
  3578,
  3596,
  3608,
  3612,
  3613,
  3650,
  3652,
  3658,
  3665,
  3680,
  3682,
  3702,
  3706,
  3716,
  3737,
  3746,
  3755,
  3762,
  3765,
  3767,
  3791,
  3810,
  3825,
  3842,
  3858,
  3861,
  3864,
  3871,
  3889,
  3897,
  3899,
  3906,
  3908,
  3920,
  3923,
  3931,
  3940,
  3947,
  3953,
  3958,
  3973,
  3980,
  3984,
  3985,
  3996,
  4026,
  4033,
  4041,
  4046,
  4051,
  4057,
  4072,
  4076,
  4102,
  4126,
  4135,
  4155,
  4159,
  4180,
  4190,
  4191,
  4216,
  4227,
  4228,
  4237,
  4245,
  4248,
  4253,
  4282,
  4286,
  4295,
  4317,
  4336,
  4347,
  4361,
  4381,
  4382,
  4386,
  4420,
  4422,
  4423,
  4430,
  4441,
  4446,
  4470,
  4482,
  4486,
  4498,
  4501,
  4505,
  4508,
  4521,
  4526,
  4536,
  4545,
  4552,
  4553,
  4573,
  4575,
  4576,
  4595,
  4601,
  4602,
  4613,
  4615,
  4634,
  4638,
  4639,
  4643,
  4645,
  4647,
  4649,
  4656,
  4664,
  4678,
  4683,
  4687,
  4690,
  4716,
  4738,
  4749,
  4753,
  4759,
  4760,
  4793,
  4796,
  4822,
  4824,
  4835,
  4839,
  4841,
  4860,
  4864,
  4877,
  4879,
  4887,
  4912,
  4933,
  4935,
  4966,
  4980,
  4984,
  4985,
  4989,
  5004,
  5015,
  5017,
  5027,
  5036,
  5058,
  5076,
  5080,
  5083,
  5084,
  5096,
  5111,
  5115,
  5119,
  5128,
  5139,
  5142,
  5147,
  5149,
  5161,
  5178,
  5188,
  5189,
  5208,
  5210,
  5227,
  5253,
  5313,
  5320,
  5343,
  5354,
  5357,
  5369,
  5374,
  5375,
  5380,
  5384,
  5406,
  5408,
  5423,
  5434,
  5443,
  5501,
  5504,
  5505,
  5520,
  5530,
  5536,
  5546,
  5551,
  5568,
  5585,
  5594,
  5605,
  5607,
  5613,
  5626,
  5640,
  5655,
  5665,
  5671,
  5720,
  5737,
  5750,
  5768,
  5770,
  5774,
  5779,
  5788,
  5807,
  5811,
  5812,
  5833,
  5851,
  5870,
  5872,
  5881,
  5890,
  5908,
  5910,
  5932,
  5935,
  5963,
  5966,
  5969,
  5990,
  6022,
  6023,
  6044,
  6060,
  6066,
  6069,
  6085,
  6098,
  6100,
  6135,
  6140,
  6152,
  6154,
  6187,
  6193,
  6212,
  6223,
  6225,
  6229,
  6239,
  6271,
  6288,
  6297,
  6306,
  6316,
  6339,
  6353,
  6358,
  6359,
  6365,
  6370,
  6376,
  6377,
  6381,
  6421,
  6423,
  6428,
  6435,
  6445,
  6448,
  6456,
  6459,
  6476,
  6507,
  6511,
  6523,
  6541,
  6544,
  6564,
  6565,
  6578,
  6594,
  6598,
  6601,
  6605,
  6619,
  6630,
  6647,
  6654,
  6655,
  6676,
  6691,
  6694,
  6709,
  6715,
  6718,
  6729,
  6732,
  6773,
  6779,
  6780,
  6799,
  6807,
  6809,
  6818,
  6828,
  6855,
  6861,
  6867,
  6892,
  6922,
  6923,
  6957,
  6961,
  6971,
  6991,
  7001,
  7008,
  7025,
  7033,
  7037,
  7038,
  7050,
  7056,
  7075,
  7091,
  7094,
  7137,
  7162,
  7168,
  7172,
  7190,
  7192,
  7196,
  7209,
  7216,
  7227,
  7234,
  7239,
  7243,
  7248,
  7249,
  7264,
  7272,
  7279,
  7289,
  7300,
  7326,
  7328,
  7330,
  7332,
  7334,
  7344,
  7356,
  7390,
  7404,
  7411,
  7428,
  7434,
  7436,
  7443,
  7459,
  7463,
  7473,
  7483,
  7499,
  7505,
  7512,
  7524,
  7549,
  7565,
  7581,
  7583,
  7584,
  7586,
  7597,
  7615,
  7616,
  7620,
  7631,
  7637,
  7647,
  7652,
  7657,
  7663,
  7665,
  7682,
  7723,
  7736,
  7738,
  7753,
  7755,
  7756,
  7802,
  7815,
  7861,
  7862,
  7875,
  7876,
  7897,
  7900,
  7904,
  7905,
  7908,
  7928,
  7940,
  7949,
  7952,
  7956,
  7994,
  8003,
  8005,
  8008,
  8023,
  8035,
  8036,
  8042,
  8044,
  8058,
  8065,
  8067,
  8099,
  8114,
  8115,
  8133,
  8160,
  8189,
  8204,
  8207,
  8219,
  8246,
  8251,
  8262,
  8264,
  8274,
  8276,
  8292,
  8304,
  8310,
  8312,
  8314,
  8334,
  8341,
  8349,
  8372,
  8380,
  8385,
  8390,
  8391,
  8411,
  8415,
  8424,
  8429,
  8434,
  8436,
  8445,
  8465,
  8485,
  8486,
  8493,
  8519,
  8521,
  8548,
  8555,
  8579,
  8603,
  8607,
  8616,
  8644,
  8647,
  8649,
  8656,
  8678,
  8690,
  8699,
  8701,
  8709,
  8726,
  8746,
  8760,
  8772,
  8793,
  8811,
  8829,
  8835,
  8861,
  8871,
  8889,
  8902,
  8913,
  8915,
  8919,
  8934,
  8967,
  8976,
  8986,
  8994,
  9016,
  9036,
  9042,
  9045,
  9047,
  9049,
  9068,
  9069,
  9081,
  9087,
  9113,
  9122,
  9123,
  9151,
  9170,
  9205,
  9213,
  9230,
  9241,
  9244,
  9248,
  9249,
  9286,
  9300,
  9314,
  9316,
  9326,
  9330,
  9355,
  9360,
  9380,
  9410,
  9424,
  9454,
  9456,
  9458,
  9479,
  9485,
  9509,
  9540,
  9548,
  9565,
  9572,
  9581,
  9583,
  9588,
  9590,
  9591,
  9593,
  9595,
  9599,
  9607,
  9622,
  9623,
  9635,
  9648,
  9659,
  9696,
  9700,
  9702,
  9729,
  9741,
  9748,
  9779,
  9784,
  9790,
  9800,
  9802,
  9808,
  9835,
  9838,
  9846,
  9849,
  9856,
  9872,
  9875,
  9880,
  9883,
  9920,
  9942,
  9950,
  9951,
  9959,
  9972,
  9992,
  9997,
  10007,
  10021,
  10049,
  10066,
  10076,
  10077,
  10084,
  10088,
  10089,
  10113,
  10151,
  10154,
  10164,
  10176,
  10197,
  10215,
  10250,
  10251,
  10256,
  10281,
  10291,
  10318,
  10338,
  10343,
  10355,
  10365,
  10401,
  10404,
  10419,
  10420,
  10422,
  10425,
  10435,
  10441,
  10450,
  10451,
  10462,
  10463,
  10485,
  10539,
  10555,
  10558,
  10561,
  10562,
  10567,
  10574,
  10577,
  ...],
 'Other': [50,
  233,
  356,
  404,
  530,
  784,
  1344,
  1624,
  1900,
  2452,
  2553,
  2605,
  2647,
  3130,
  3207,
  3238,
  3343,
  3350,
  3380,
  3453,
  3555,
  3635,
  3672,
  3743,
  4457,
  4462,
  4700,
  4718,
  4732,
  4962,
  5028,
  5118,
  5207,
  5254,
  5290,
  5399,
  5510,
  5586,
  5623,
  5663,
  5758,
  6001,
  6057,
  6131,
  6203,
  6240,
  6518,
  6672,
  6878,
  7080,
  7189,
  7238,
  7600,
  7659,
  7700,
  7882,
  7891,
  8016,
  8124,
  8178,
  8438,
  8516,
  8710,
  8734,
  8847,
  8924,
  8943,
  8947,
  9015,
  9065,
  9072,
  9118,
  9155,
  9252,
  9277,
  9346,
  9543,
  9554,
  9658,
  9739,
  9843,
  9869,

In [94]:
grouped1= df.groupby(["race","sex"])

In [97]:
grouped1.mean()

                                 age         fnlwgt  education-num  \
race               sex
Amer-Indian-Eskimo Female  37.117647  112950.731092       9.697479
                   Male    37.208333  125715.364583       9.072917
Asian-Pac-Islander Female  35.089595  147452.075145      10.390173
                   Male    39.073593  166175.865801      11.245310
Black              Female  37.854019  212971.387781       9.549839
                   Male    37.682600  242920.644997       9.423199
Other              Female  31.678899  172519.642202       8.899083
                   Male    34.654321  213679.104938       8.802469
White              Female  36.811618  183549.966906      10.127980
                   Male    39.652498  188987.386148      10.138521

                           capital-gain  capital-loss  hours-per-week
race               sex
Amer-Indian-Eskimo Female    544.605042     14.462185       36.579832
                   Male      675.260417     46.395833       42.197917
Asian-Pac-Islander Female    778.436416     50.852601       37.439306
                   Male     1827.813853    120.373737       41.468975
Black              Female    516.593569     45.450804       36.834084
                   Male      702.454430     75.186106       39.997451
Other              Female    254.669725     36.284404       35.926606
                   Male     1392.185185     77.746914       41.851852
White              Female    573.610391     65.390535       36.296691
                   Male     1368.674455    102.261343       42.668822

In [98]:
grouped1.size()

race                sex
Amer-Indian-Eskimo  Female      119
                    Male        192
Asian-Pac-Islander  Female      346
                    Male        693
Black               Female     1555
                    Male       1569
Other               Female      109
                    Male        162
White               Female     8642
                    Male      19174
dtype: int64

In [99]:
grouped.get_group("White")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
30,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
32,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
33,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
35,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
36,21,Private,197200,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
37,19,Private,544091,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
38,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
39,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
40,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
41,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
42,24,Private,172987,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32522,58,Private,147707,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
32523,30,Private,77266,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,55,United-States,<=50K
32524,26,Private,191648,Assoc-acdm,12,Never-married,Machine-op-inspct,Other-relative,White,Female,0,0,15,United-States,<=50K
32525,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K
32526,32,Private,211349,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
32527,22,Private,203715,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
32528,31,Private,292592,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
32529,29,Private,125976,HS-grad,9,Separated,Sales,Unmarried,White,Female,0,0,35,United-States,<=50K
32530,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [104]:
grouped1.get_group(("White","Female"))  #以元祖方式传入

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
37,19,Private,544091,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
43,49,Private,94638,HS-grad,9,Separated,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
47,44,Private,128354,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
51,18,Private,226956,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,30,?,<=50K
52,47,Private,51835,Prof-school,15,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,1902,60,Honduras,>50K
66,28,Private,183175,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
67,53,Private,169846,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,>50K
78,18,Private,309634,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,22,United-States,<=50K
82,46,Private,51618,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,United-States,<=50K
84,44,Private,343591,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,14344,0,40,United-States,>50K
85,53,Private,346253,HS-grad,9,Divorced,Sales,Own-child,White,Female,0,0,35,United-States,<=50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
91,37,Private,286730,Some-college,10,Divorced,Craft-repair,Unmarried,White,Female,0,0,40,United-States,<=50K
98,48,Private,171095,Assoc-acdm,12,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,England,<=50K
102,47,Self-emp-not-inc,149116,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
103,20,Private,188300,Some-college,10,Never-married,Tech-support,Own-child,White,Female,0,0,40,United-States,<=50K
106,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,<=50K
108,31,Local-gov,189265,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
113,28,Private,377869,Some-college,10,Married-civ-spouse,Sales,Wife,White,Female,4064,0,25,United-States,<=50K
114,36,Private,102864,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Female,0,0,40,United-States,<=50K
120,21,Private,199915,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,<=50K
125,47,Private,287828,Bachelors,13,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
126,20,Private,111697,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,1719,28,United-States,<=50K
130,28,Private,69621,Assoc-acdm,12,Never-married,Sales,Not-in-family,White,Female,0,0,60,United-States,<=50K
131,24,Private,43323,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,1762,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32465,66,Private,269665,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,0,25,United-States,<=50K
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
32470,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
32473,41,Federal-gov,160467,Masters,14,Divorced,Prof-specialty,Unmarried,White,Female,1506,0,40,United-States,<=50K
32481,52,Private,301229,Assoc-voc,11,Separated,Sales,Unmarried,White,Female,0,0,40,United-States,<=50K
32483,27,Private,155382,Some-college,10,Never-married,Other-service,Not-in-family,White,Female,0,0,25,United-States,<=50K
32484,48,Private,268083,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
32485,28,Private,113987,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
32493,24,Private,381895,11th,7,Divorced,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
32497,34,Private,321709,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,28,United-States,<=50K
32504,50,Private,208630,Masters,14,Divorced,Sales,Not-in-family,White,Female,0,0,50,United-States,>50K
32509,32,Private,192965,HS-grad,9,Separated,Sales,Not-in-family,White,Female,0,0,45,United-States,<=50K
32513,46,Private,42972,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,22,United-States,>50K
32516,30,Private,176175,Assoc-voc,11,Divorced,Adm-clerical,Unmarried,White,Female,0,0,24,United-States,<=50K
32520,27,Private,177398,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,64,United-States,<=50K
32524,26,Private,191648,Assoc-acdm,12,Never-married,Machine-op-inspct,Other-relative,White,Female,0,0,15,United-States,<=50K
32525,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K
32528,31,Private,292592,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
32529,29,Private,125976,HS-grad,9,Separated,Sales,Unmarried,White,Female,0,0,35,United-States,<=50K
32530,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [105]:
for name ,group in grouped1:
    print(name)
    print(group.shape)

('Amer-Indian-Eskimo', 'Female')
(119, 15)
('Amer-Indian-Eskimo', 'Male')
(192, 15)
('Asian-Pac-Islander', 'Female')
(346, 15)
('Asian-Pac-Islander', 'Male')
(693, 15)
('Black', 'Female')
(1555, 15)
('Black', 'Male')
(1569, 15)
('Other', 'Female')
(109, 15)
('Other', 'Male')
(162, 15)
('White', 'Female')
(8642, 15)
('White', 'Male')
(19174, 15)

In [106]:
grouped1.mean()

                                 age         fnlwgt  education-num  \
race               sex
Amer-Indian-Eskimo Female  37.117647  112950.731092       9.697479
                   Male    37.208333  125715.364583       9.072917
Asian-Pac-Islander Female  35.089595  147452.075145      10.390173
                   Male    39.073593  166175.865801      11.245310
Black              Female  37.854019  212971.387781       9.549839
                   Male    37.682600  242920.644997       9.423199
Other              Female  31.678899  172519.642202       8.899083
                   Male    34.654321  213679.104938       8.802469
White              Female  36.811618  183549.966906      10.127980
                   Male    39.652498  188987.386148      10.138521

                           capital-gain  capital-loss  hours-per-week
race               sex
Amer-Indian-Eskimo Female    544.605042     14.462185       36.579832
                   Male      675.260417     46.395833       42.197917
Asian-Pac-Islander Female    778.436416     50.852601       37.439306
                   Male     1827.813853    120.373737       41.468975
Black              Female    516.593569     45.450804       36.834084
                   Male      702.454430     75.186106       39.997451
Other              Female    254.669725     36.284404       35.926606
                   Male     1392.185185     77.746914       41.851852
White              Female    573.610391     65.390535       36.296691
                   Male     1368.674455    102.261343       42.668822

#### aggregation

In [11]:
help(pd.aggregation)

AttributeError: module 'pandas' has no attribute 'aggregation'

In [108]:
grouped1.agg([np.sum,np.mean,np.median])

                              age                        fnlwgt          \
                              sum       mean median         sum    mean
race               sex
Amer-Indian-Eskimo Female    4417  37.117647     36    13441137  112950
                   Male      7144  37.208333     35    24137350  125715
Asian-Pac-Islander Female   12141  35.089595     33    51018418  147452
                   Male     27078  39.073593     37   115159875  166175
Black              Female   58863  37.854019     37   331170508  212971
                   Male     59124  37.682600     36   381142492  242920
Other              Female    3453  31.678899     29    18804641  172519
                   Male      5614  34.654321     32    34616015  213679
White              Female  318126  36.811618     35  1586238814  183549
                   Male    760297  39.652498     38  3623644142  188987

                                  education-num                    \
                           median           sum       mean median
race               sex
Amer-Indian-Eskimo Female   87950          1154   9.697479     10
                   Male    113091          1742   9.072917      9
Asian-Pac-Islander Female  131986          3595  10.390173     10
                   Male    147719          7793  11.245310     11
Black              Female  193553         14850   9.549839      9
                   Male    221196         14785   9.423199      9
Other              Female  171199           970   8.899083      9
                   Male    208516          1426   8.802469      9
White              Female  175810         87526  10.127980     10
                   Male    178662        194396  10.138521     10

                          capital-gain                     capital-loss  \
                                   sum         mean median          sum
race               sex
Amer-Indian-Eskimo Female        64808   544.605042      0         1721
                   Male         129650   675.260417      0         8908
Asian-Pac-Islander Female       269339   778.436416      0        17595
                   Male        1266675  1827.813853      0        83419
Black              Female       803303   516.593569      0        70676
                   Male        1102151   702.454430      0       117967
Other              Female        27759   254.669725      0         3955
                   Male         225534  1392.185185      0        12595
White              Female      4957141   573.610391      0       565105
                   Male       26242964  1368.674455      0      1960759

                                             hours-per-week
                                 mean median            sum       mean median
race               sex
Amer-Indian-Eskimo Female   14.462185      0           4353  36.579832     40
                   Male     46.395833      0           8102  42.197917     40
Asian-Pac-Islander Female   50.852601      0          12954  37.439306     40
                   Male    120.373737      0          28738  41.468975     40
Black              Female   45.450804      0          57277  36.834084     40
                   Male     75.186106      0          62756  39.997451     40
Other              Female   36.284404      0           3916  35.926606     40
                   Male     77.746914      0           6780  41.851852     40
White              Female   65.390535      0         313676  36.296691     40
                   Male    102.261343      0         818132  42.668822     40

In [110]:
grouped1["age"].agg([np.sum,np.mean,np.median])

                              sum       mean  median
race               sex
Amer-Indian-Eskimo Female    4417  37.117647      36
                   Male      7144  37.208333      35
Asian-Pac-Islander Female   12141  35.089595      33
                   Male     27078  39.073593      37
Black              Female   58863  37.854019      37
                   Male     59124  37.682600      36
Other              Female    3453  31.678899      29
                   Male      5614  34.654321      32
White              Female  318126  36.811618      35
                   Male    760297  39.652498      38

In [111]:
grouped1["age"].agg({"求和":np.sum,"求平均数":np.mean})# 对指定一列用字典的方式对agg结果重新命名

                               求和       求平均数
race               sex
Amer-Indian-Eskimo Female    4417  37.117647
                   Male      7144  37.208333
Asian-Pac-Islander Female   12141  35.089595
                   Male     27078  39.073593
Black              Female   58863  37.854019
                   Male     59124  37.682600
Other              Female    3453  31.678899
                   Male      5614  34.654321
White              Female  318126  36.811618
                   Male    760297  39.652498

In [112]:
grouped1.agg({"求和":np.sum,"求平均数":np.mean})#对全部列用字典的方式对agg结果重新命名会报错

KeyError: '求和'

In [114]:
grouped1["age","fnlwgt"].agg({"求和":np.sum,"求平均数":np.mean})#对指定多个列用字典的方式对agg结果重新命名

                               求和                   求平均数
                              age      fnlwgt        age         fnlwgt
race               sex
Amer-Indian-Eskimo Female    4417    13441137  37.117647  112950.731092
                   Male      7144    24137350  37.208333  125715.364583
Asian-Pac-Islander Female   12141    51018418  35.089595  147452.075145
                   Male     27078   115159875  39.073593  166175.865801
Black              Female   58863   331170508  37.854019  212971.387781
                   Male     59124   381142492  37.682600  242920.644997
Other              Female    3453    18804641  31.678899  172519.642202
                   Male      5614    34616015  34.654321  213679.104938
White              Female  318126  1586238814  36.811618  183549.966906
                   Male    760297  3623644142  39.652498  188987.386148

#### 假如你想要对age 求平均，但对fnlwgt求和

In [116]:
grouped1.agg({"age":np.mean, "fnlwgt":np.sum})

                                 age      fnlwgt
race               sex
Amer-Indian-Eskimo Female  37.117647    13441137
                   Male    37.208333    24137350
Asian-Pac-Islander Female  35.089595    51018418
                   Male    39.073593   115159875
Black              Female  37.854019   331170508
                   Male    37.682600   381142492
Other              Female  31.678899    18804641
                   Male    34.654321    34616015
White              Female  36.811618  1586238814
                   Male    39.652498  3623644142

In [ ]:
grouped1.agg({"求和":np.sum,"求平均数":np.mean}) #找不到名字为“求和”的这一列
# 错误的写法

### 假如你想要对age 求平均，但对fnlwgt求和    
##### 对于不同的列使用不同的方法      
   ** grouped1.agg({"age":np.mean, "fnlwgt":np.sum})**    
#### 重新命名        
   **grouped1["age","fnlwgt"].agg({"求和":np.sum,"求平均数":np.mean})**

In [157]:
df1= df.set_index(["race","sex"])    # 注意[]不要少

In [153]:
df1

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,sex,capital-gain,capital-loss,hours-per-week,native-country,class
race,,,,,,,,,,,,,,
White,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,Male,2174,0,40,United-States,<=50K
White,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,13,United-States,<=50K
White,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,Male,0,0,40,United-States,<=50K
Black,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Male,0,0,40,United-States,<=50K
Black,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Female,0,0,40,Cuba,<=50K
White,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,Female,0,0,40,United-States,<=50K
Black,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Female,0,0,16,Jamaica,<=50K
White,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,45,United-States,>50K
White,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,Female,14084,0,50,United-States,>50K
White,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,5178,0,40,United-States,>50K
Black,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,80,United-States,>50K
Asian-Pac-Islander,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Male,0,0,40,India,>50K
White,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,Female,0,0,30,United-States,<=50K
Black,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Male,0,0,50,United-States,<=50K
Asian-Pac-Islander,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Male,0,0,40,?,>50K
Amer-Indian-Eskimo,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Male,0,0,45,Mexico,<=50K
White,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,Male,0,0,35,United-States,<=50K
White,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,Male,0,0,40,United-States,<=50K
White,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,Male,0,0,50,United-States,<=50K
White,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,Female,0,0,45,United-States,>50K
White,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Male,0,0,60,United-States,>50K
Black,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Female,0,0,20,United-States,<=50K
Black,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Male,0,0,40,United-States,<=50K
White,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,Male,0,2042,40,United-States,<=50K
White,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,Female,0,0,40,United-States,<=50K
White,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,Male,0,0,40,United-States,>50K
White,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,Male,0,0,40,United-States,<=50K
Asian-Pac-Islander,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Male,0,0,60,South,>50K
White,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,Male,0,0,80,United-States,<=50K
White,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Asian-Pac-Islander,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Female,0,0,99,United-States,<=50K
White,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Male,0,0,60,United-States,>50K
Asian-Pac-Islander,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,50,Japan,>50K
White,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,Female,0,0,39,United-States,<=50K
Black,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Male,0,0,35,United-States,<=50K
White,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,Female,0,0,55,United-States,>50K
Black,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Male,0,0,46,United-States,<=50K
Black,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Female,15020,0,45,United-States,>50K
White,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,Male,0,0,10,United-States,>50K
White,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,Female,0,0,40,United-States,<=50K
Black,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Female,0,0,32,United-States,<=50K
White,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,Male,0,0,25,United-States,<=50K
White,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,Female,0,0,48,United-States,<=50K
Other,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Female,0,0,30,United-States,<=50K
White,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,Female,0,0,20,United-States,>50K
White,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,Female,0,0,40,United-States,<=50K
White,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Male,0,0,40,Mexico,<=50K
White,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Male,1086,0,60,United-States,<=50K
White,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,Female,0,0,40,United-States,<=50K
White,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,Male,0,0,50,United-States,<=50K
Amer-Indian-Eskimo,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Male,0,0,40,United-States,<=50K
White,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,Male,0,0,45,United-States,<=50K
Asian-Pac-Islander,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Male,0,0,11,Taiwan,<=50K
White,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,40,United-States,>50K
White,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,Male,0,0,40,United-States,<=50K
White,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,Female,0,0,38,United-States,<=50K
White,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Male,0,0,40,United-States,>50K
White,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,Female,0,0,40,United-States,<=50K
White,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,Male,0,0,20,United-States,<=50K
White,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,Female,15024,0,40,United-States,>50K

In [130]:
help(pd.groupby)

Help on function groupby in module pandas.core.groupby:

groupby(obj, by, **kwds)
    Class for grouping and aggregating relational data. See aggregate,
    transform, and apply functions on this object.

    It's easiest to use obj.groupby(...) to use GroupBy, but you can also do:

    ::

        grouped = groupby(obj, ...)

    Parameters
    ----------
    obj : pandas object
    axis : int, default 0
    level : int, default None
        Level of MultiIndex
    groupings : list of Grouping objects
        Most users should ignore this
    exclusions : array-like, optional
        List of columns to exclude
    name : string
        Most users should ignore this

    Notes
    -----
    After grouping, see aggregate, apply, and transform functions. Here are
    some other brief notes about usage. When grouping by multiple groups, the
    result index will be a MultiIndex (hierarchical) by default.

    Iteration produces (key, group) tuples, i.e. chunking the data by group. So
    you can write code like:

    ::

        grouped = obj.groupby(keys, axis=axis)
        for key, group in grouped:
            # do something with the data

    Function calls on GroupBy, if not specially implemented, "dispatch" to the
    grouped data. So if you group a DataFrame and wish to invoke the std()
    method on each group, you can simply do:

    ::

        df.groupby(mapper).std()

    rather than

    ::

        df.groupby(mapper).aggregate(np.std)

    You can pass arguments to these "wrapped" functions, too.

    See the online documentation for full exposition on these topics and much
    more

    Returns
    -------
    **Attributes**
    groups : dict
        {group name -> group labels}
    len(grouped) : int
        Number of groups

In [156]:
groupedIndex = df1.groupby(level =[0,1])

In [158]:
groupedIndex.size()

race                sex
Amer-Indian-Eskimo  Female      119
                    Male        192
Asian-Pac-Islander  Female      346
                    Male        693
Black               Female     1555
                    Male       1569
Other               Female      109
                    Male        162
White               Female     8642
                    Male      19174
dtype: int64

### Transformation

In [146]:
age = df.age

In [143]:
age.mean()

38.58164675532078

In [144]:
age.std()

13.640432553581146

In [145]:
(age - age.mean())/ age.std()

0        0.030670
1        0.837096
2       -0.042641
3        1.057031
4       -0.775756
5       -0.115953
6        0.763785
7        0.983719
8       -0.555822
9        0.250604
10      -0.115953
11      -0.629133
12      -1.142313
13      -0.482510
14       0.103982
15      -0.335887
16      -0.995690
17      -0.482510
18      -0.042641
19       0.323916
20       0.103982
21       1.130342
22      -0.262576
23       0.323916
24       1.496899
25       1.276965
26      -1.435559
27       1.130342
28       0.030670
29       0.763785
           ...
32531   -0.629133
32532   -0.335887
32533    1.130342
32534   -0.115953
32535   -1.215625
32536   -0.335887
32537   -0.629133
32538   -0.042641
32539    2.376637
32540    0.470539
32541    0.177293
32542    2.449948
32543    0.470539
32544   -0.555822
32545    0.030670
32546   -0.115953
32547    0.323916
32548    1.936768
32549    0.323916
32550    0.323916
32551   -0.482510
32552    0.323916
32553   -0.482510
32554    1.057031
32555   -1.215625
32556   -0.849067
32557    0.103982
32558    1.423588
32559   -1.215625
32560    0.983719
Name: age, dtype: float64

In [148]:
df.std()  # 可以对数据框的数字型数据进行函数运算

age                   13.640433
fnlwgt            105549.977697
education-num          2.572720
capital-gain        7385.292085
capital-loss         402.960219
hours-per-week        12.347429
dtype: float64

In [147]:
zscore = lambda s: (s-s.mean())/ s.std()

In [149]:
#不同种族，不同性别的人 这个数据进行标准化
grouped1.transform(zscore)    #对每个group做标准化，在组合起来

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
0,-0.048563,-1.074790,1.077176,0.095386,-0.235540,-0.218852
1,0.770131,-1.018915,1.077176,-0.162111,-0.235540,-2.432941
2,-0.122990,0.257038,-0.428585,-0.162111,-0.235540,-0.218852
3,1.188998,-0.061125,-1.016937,-0.141564,-0.202671,0.000234
4,-0.779763,1.140640,1.562704,-0.097237,-0.151959,0.336086
5,0.013147,0.993331,1.635064,-0.120427,-0.185594,0.303775
6,0.881998,-0.479983,-2.060789,-0.097237,-0.151959,-2.211696
7,0.918984,0.199149,-0.428585,-0.162111,-0.235540,0.191164
8,-0.405582,-1.354523,1.635064,2.836451,-0.185594,1.124056
9,0.174717,-0.284805,1.077176,0.451191,-0.235540,-0.218852
10,-0.052986,0.279869,0.242064,-0.141564,-0.202671,3.666792
11,-0.704256,-0.280949,0.631760,-0.166961,-0.254534,-0.118585
12,-0.963886,-0.602476,1.212788,-0.120427,-0.185594,-0.516505
13,-0.441106,-0.282540,1.081398,-0.141564,-0.202671,0.916873
14,0.071904,-0.501439,-0.088322,-0.166961,-0.254534,-0.118585
15,-0.266261,1.408030,-2.236157,-0.230484,-0.161905,0.241636
16,-1.090538,-0.117933,-0.428585,-0.162111,-0.235540,-0.628869
17,-0.569551,-0.020859,-0.428585,-0.162111,-0.235540,-0.218852
18,-0.122990,-1.543663,-1.181465,-0.162111,-0.235540,0.601181
19,0.431875,1.067985,1.635064,-0.120427,-0.185594,0.713916
20,0.025863,0.043741,2.206496,-0.162111,-0.235540,1.421214
21,1.277655,0.810890,-0.249042,-0.097237,-0.151959,-1.787065
22,-0.208234,-1.238022,-1.856271,-0.141564,-0.202671,0.000234
23,0.249144,-0.693734,-1.181465,-0.162111,4.467828,-0.218852
24,1.548485,-0.732816,-0.476320,-0.120427,-0.185594,0.303775
25,1.216691,0.268657,1.077176,-0.162111,-0.235540,-0.218852
26,-1.537098,-0.199522,-0.428585,-0.162111,-0.235540,-0.218852
27,1.158528,0.158494,-0.448362,-0.166961,-0.254534,1.495938
28,-0.048563,1.718877,-0.428585,-0.162111,-0.235540,3.061279
29,0.695704,0.042218,-0.428585,-0.162111,-0.235540,-0.218852
...,...,...,...,...,...,...
32531,-0.413760,-1.487417,0.933198,-0.101422,-0.171493,4.932962
32532,-0.420697,0.149194,2.206496,-0.162111,-0.235540,1.421214
32533,1.158528,1.940264,0.631760,-0.166961,-0.254534,0.688677
32534,0.013147,-0.043388,-0.054043,-0.120427,-0.185594,0.221747
32535,-1.217346,0.612112,-0.597270,-0.141564,-0.202671,-0.458086
32536,-0.196217,-0.229416,1.212788,-0.120427,-0.185594,1.534196
32537,-0.596354,0.767651,-0.177603,-0.141564,-0.202671,0.550217
32538,0.011552,-0.671006,1.562704,2.729925,-0.151959,0.866874
32539,2.333093,0.948609,2.206496,-0.162111,-0.235540,-2.678951
32540,0.571452,0.675035,-0.476320,-0.120427,-0.185594,0.303775
32541,0.248946,-0.092291,-0.249042,-0.097237,-0.151959,-0.513175
32542,2.407520,-0.569596,-0.428585,-0.162111,-0.235540,-1.448902
32543,0.571452,-0.632689,0.790511,-0.120427,-0.185594,0.960000
32544,-0.058367,0.348933,1.684871,-0.193323,-0.156535,-0.575356
32545,0.152723,-0.708394,0.790511,-0.120427,-0.185594,-1.336786
32546,0.013147,0.144194,0.790511,-0.120427,-0.185594,0.303775
32547,0.249144,0.692030,-0.428585,-0.162111,-0.235540,-0.218852
32548,1.886532,-0.864183,1.830056,-0.033481,-0.235540,1.421214
32549,0.431875,0.710695,-0.054043,-0.120427,-0.185594,0.303775
32550,0.249144,-1.559524,-0.052145,-0.162111,-0.235540,0.601181
32551,-0.432243,-1.077426,-1.354551,-0.230484,-0.161905,-0.189536
32552,0.249144,-1.005899,0.324295,-0.162111,-0.235540,0.191164
32553,-0.549024,-0.565062,0.991801,-0.166961,-0.254534,-2.459642
32554,0.993411,1.281185,1.453616,-0.162111,-0.235540,-0.218852
32555,-1.313818,1.168250,-0.052145,-0.162111,-0.235540,-0.218852
32556,-0.684734,0.725119,0.790511,-0.120427,-0.185594,0.139719
32557,0.025863,-0.333737,-0.428585,-0.162111,-0.235540,-0.218852
32558,1.478697,-0.311079,-0.476320,-0.120427,-0.185594,0.303775
32559,-1.313818,0.120548,-0.428585,-0.162111,-0.235540,-1.858918
32560,1.059968,1.026219,-0.476320,3.033800,-0.185594,0.303775

* Transformation：会返回一个数据集，这个数据集与group具有同样的索引以及大小         
举例说明：                  
对数据集进行标准化：                                      
zscore = lambda s : (s –s.mean()) / s.td()                   
transformed = df.groupby(key).transform(zscore)

## Filtration
返回原始数据集的一个子集

In [160]:
grouped1.size()

race                sex
Amer-Indian-Eskimo  Female      119
                    Male        192
Asian-Pac-Islander  Female      346
                    Male        693
Black               Female     1555
                    Male       1569
Other               Female      109
                    Male        162
White               Female     8642
                    Male      19174
dtype: int64

In [164]:
#过滤grouped1 小组里样本数小于1000的，保留剩下的样本
grouped1.filter(lambda s : s.shape[0] >= 1000).shape

(30940, 15)

In [166]:
df.shape

(32561, 15)

In [167]:
grouped1.filter(lambda s : np.mean(s["age"]) >= 37).shape # s指的是每个小组，不是样本

(23302, 15)

## 多表操作

## concat

In [169]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                     index=[0, 1, 2, 3])   

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])
    
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                       'D': ['D8', 'D9', 'D10', 'D11']},
                      index=[8, 9, 10, 11])
 
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                  'D': ['D2', 'D3', 'D6', 'D7'],
                 'F': ['F2', 'F3', 'F6', 'F7']},
                 index=[2, 3, 6, 7])

In [170]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [171]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [172]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [174]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [175]:
df4

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [176]:
pd.concat([df3,df4])

      A    B    C    D    F
8    A8   B8   C8   D8  NaN
9    A9   B9   C9   D9  NaN
10  A10  B10  C10  D10  NaN
11  A11  B11  C11  D11  NaN
2   NaN   B2  NaN   D2   F2
3   NaN   B3  NaN   D3   F3
6   NaN   B6  NaN   D6   F6
7   NaN   B7  NaN   D7   F7

In [178]:
pd.concat([df3,df4],ignore_index=True)  #忽视原先的索引

     A    B    C    D    F
0   A8   B8   C8   D8  NaN
1   A9   B9   C9   D9  NaN
2  A10  B10  C10  D10  NaN
3  A11  B11  C11  D11  NaN
4  NaN   B2  NaN   D2   F2
5  NaN   B3  NaN   D3   F3
6  NaN   B6  NaN   D6   F6
7  NaN   B7  NaN   D7   F7

In [177]:
pd.concat([df3,df4],axis=1)

      A    B    C    D    B    D    F
2   NaN  NaN  NaN  NaN   B2   D2   F2
3   NaN  NaN  NaN  NaN   B3   D3   F3
6   NaN  NaN  NaN  NaN   B6   D6   F6
7   NaN  NaN  NaN  NaN   B7   D7   F7
8    A8   B8   C8   D8  NaN  NaN  NaN
9    A9   B9   C9   D9  NaN  NaN  NaN
10  A10  B10  C10  D10  NaN  NaN  NaN
11  A11  B11  C11  D11  NaN  NaN  NaN

In [181]:
df1.append(df2).append(df3).append(df4)

      A    B    C    D    F
0    A0   B0   C0   D0  NaN
1    A1   B1   C1   D1  NaN
2    A2   B2   C2   D2  NaN
3    A3   B3   C3   D3  NaN
4    A4   B4   C4   D4  NaN
5    A5   B5   C5   D5  NaN
6    A6   B6   C6   D6  NaN
7    A7   B7   C7   D7  NaN
8    A8   B8   C8   D8  NaN
9    A9   B9   C9   D9  NaN
10  A10  B10  C10  D10  NaN
11  A11  B11  C11  D11  NaN
2   NaN   B2  NaN   D2   F2
3   NaN   B3  NaN   D3   F3
6   NaN   B6  NaN   D6   F6
7   NaN   B7  NaN   D7   F7

In [182]:
help(df1.append)

Help on method append in module pandas.core.frame:

append(other, ignore_index=False, verify_integrity=False) method of pandas.core.frame.DataFrame instance
    Append rows of `other` to the end of this frame, returning a new
    object. Columns not in this frame are added as new columns.

    Parameters
    ----------
    other : DataFrame or Series/dict-like object, or list of these
        The data to append.
    ignore_index : boolean, default False
        If True, do not use the index labels.
    verify_integrity : boolean, default False
        If True, raise ValueError on creating index with duplicates.

    Returns
    -------
    appended : DataFrame

    Notes
    -----
    If a list of dict/series is passed and the keys are all contained in
    the DataFrame's index, the order of the columns in the resulting
    DataFrame will be unchanged.

    See also
    --------
    pandas.concat : General function to concatenate DataFrame, Series
        or Panel objects

    Examples
    --------

    >>> df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
    >>> df
       A  B
    0  1  2
    1  3  4
    >>> df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))
    >>> df.append(df2)
       A  B
    0  1  2
    1  3  4
    0  5  6
    1  7  8

    With `ignore_index` set to True:

    >>> df.append(df2, ignore_index=True)
       A  B
    0  1  2
    1  3  4
    2  5  6
    3  7  8

## merge
joining key columns              
joining key indexes                     
joining key columns on indexes

In [184]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})
 

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                       'key2': ['K0', 'K0', 'K0', 'K0'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [185]:
left

    A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [186]:
right

    C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [188]:
pd.merge(left,right,on=["key1","key2"],how = "inner")#inner指的是两表key相交得到的集合

    A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [190]:
pd.merge(left,right,on=["key1","key2"],how = "left")#以left表的主键为主

    A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [193]:
pd.merge(left,right,on=["key1","key2"],how = "outer") #两张表主键求并的结果

     A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [194]:
left1 = left.rename(columns={"key1":"key1_L","key2":"key2_L"})

In [195]:
left1

    A   B key1_L key2_L
0  A0  B0     K0     K0
1  A1  B1     K0     K1
2  A2  B2     K1     K0
3  A3  B3     K2     K1

In [197]:
pd.merge(left1,right,left_on = ["key1_L","key2_L"],right_on = ["key1","key2"],how = "inner")

    A   B key1_L key2_L   C   D key1 key2
0  A0  B0     K0     K0  C0  D0   K0   K0
1  A2  B2     K1     K0  C1  D1   K1   K0
2  A2  B2     K1     K0  C2  D2   K1   K0

#### 对于主键不同的列，不能同之前的方法，直接一个on（，），要分开写left_on，right_on，但是两个表的键要对应，就是说，key1_L与key1相对应。

In [198]:
left2 = left.set_index(["key1","key2"])

In [199]:
left2      #  "key1","key2"在这个表的索引上，不是在列上

            A   B
key1 key2
K0   K0    A0  B0
     K1    A1  B1
K1   K0    A2  B2
K2   K1    A3  B3

In [200]:
pd.merge(left2,right,right_on=["key1","key2"],left_index=True)

    A   B   C   D key1 key2
0  A0  B0  C0  D0   K0   K0
1  A2  B2  C1  D1   K1   K0
2  A2  B2  C2  D2   K1   K0

#### 左表里的索引与右表里的主键在数量与位置上要一一对应，要求比较严苛。

In [201]:
right2 = right.set_index(["key1","key2"])

In [202]:
right2

            C   D
key1 key2
K0   K0    C0  D0
K1   K0    C1  D1
     K0    C2  D2
K2   K0    C3  D3

In [206]:
pd.merge(left2,right2,right_index=True,left_index=True)

            A   B   C   D
key1 key2
K0   K0    A0  B0  C0  D0
K1   K0    A2  B2  C1  D1
     K0    A2  B2  C2  D2

In [209]:
help(pd.merge)

Help on function merge in module pandas.tools.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
    Merge DataFrame objects by performing a database-style join operation by
    columns or indexes.

    If joining columns on columns, the DataFrame indexes *will be
    ignored*. Otherwise if joining indexes on indexes or indexes on a column or
    columns, the index will be passed on.

    Parameters
    ----------
    left : DataFrame
    right : DataFrame
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        * left: use only keys from left frame (SQL: left outer join)
        * right: use only keys from right frame (SQL: right outer join)
        * outer: use union of keys from both frames (SQL: full outer join)
        * inner: use intersection of keys from both frames (SQL: inner join)
    on : label or list
        Field names to join on. Must be found in both DataFrames. If on is
        None and not merging on indexes, then it merges on the intersection of
        the columns by default.
    left_on : label or list, or array-like
        Field names to join on in left DataFrame. Can be a vector or list of
        vectors of the length of the DataFrame to use a particular vector as
        the join key instead of columns
    right_on : label or list, or array-like
        Field names to join on in right DataFrame or vector/list of vectors per
        left_on docs
    left_index : boolean, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels
    right_index : boolean, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index
    sort : boolean, default False
        Sort the join keys lexicographically in the result DataFrame
    suffixes : 2-length sequence (tuple, list, ...)
        Suffix to apply to overlapping column names in the left and right
        side, respectively
    copy : boolean, default True
        If False, do not copy data unnecessarily
    indicator : boolean or string, default False
        If True, adds a column to output DataFrame called "_merge" with
        information on the source of each row.
        If string, column with information on source of each row will be added to
        output DataFrame, and column will be named value of string.
        Information column is Categorical-type and takes on a value of "left_only"
        for observations whose merge key only appears in 'left' DataFrame,
        "right_only" for observations whose merge key only appears in 'right'
        DataFrame, and "both" if the observation's merge key is found in both.

        .. versionadded:: 0.17.0

    Examples
    --------

    >>> A              >>> B
        lkey value         rkey value
    0   foo  1         0   foo  5
    1   bar  2         1   bar  6
    2   baz  3         2   qux  7
    3   foo  4         3   bar  8

    >>> A.merge(B, left_on='lkey', right_on='rkey', how='outer')
       lkey  value_x  rkey  value_y
    0  foo   1        foo   5
    1  foo   4        foo   5
    2  bar   2        bar   6
    3  bar   2        bar   8
    4  baz   3        NaN   NaN
    5  NaN   NaN      qux   7

    Returns
    -------
    merged : DataFrame
        The output type will the be same as 'left', if it is a subclass
        of DataFrame.

## Join
* 组合dataframe 的一种快捷方式，它默认的是在索引上进行Join           
* join有一个参数on，可以指定一个或者多个columns，但是这只对最左边的数据集有效，右边的数据集的key还是索引

In [210]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                     index=pd.Index(['K0', 'K1', 'K2'], name='key'))


index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                 ('K2', 'Y2'), ('K2', 'Y3')],
                                  names=['key', 'Y'])


right = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']},
                      index=index)

In [211]:
left

      A   B
key
K0   A0  B0
K1   A1  B1
K2   A2  B2

In [212]:
right

         C   D
key Y
K0  Y0  C0  D0
K1  Y1  C1  D1
K2  Y2  C2  D2
    Y3  C3  D3

In [ ]:
left.join(right,)
#right 只能用索引 left 用的是列名  即： right_index = True,left_on=....

In [213]:
right2

            C   D
key1 key2
K0   K0    C0  D0
K1   K0    C1  D1
     K0    C2  D2
K2   K0    C3  D3

In [216]:
help(left.join)

Help on method join in module pandas.core.frame:

join(other, on=None, how='left', lsuffix='', rsuffix='', sort=False) method of pandas.core.frame.DataFrame instance
    Join columns with other DataFrame either on index or on a key
    column. Efficiently Join multiple DataFrame objects by index at once by
    passing a list.

    Parameters
    ----------
    other : DataFrame, Series with name field set, or list of DataFrame
        Index should be similar to one of the columns in this one. If a
        Series is passed, its name attribute must be set, and that will be
        used as the column name in the resulting joined DataFrame
    on : column name, tuple/list of column names, or array-like
        Column(s) to use for joining, otherwise join on index. If multiples
        columns given, the passed DataFrame must have a MultiIndex. Can
        pass an array as the join key if not already contained in the
        calling DataFrame. Like an Excel VLOOKUP operation
    how : {'left', 'right', 'outer', 'inner'}
        How to handle indexes of the two objects. Default: 'left'
        for joining on index, None otherwise

        * left: use calling frame's index
        * right: use input frame's index
        * outer: form union of indexes
        * inner: use intersection of indexes
    lsuffix : string
        Suffix to use from left frame's overlapping columns
    rsuffix : string
        Suffix to use from right frame's overlapping columns
    sort : boolean, default False
        Order result DataFrame lexicographically by the join key. If False,
        preserves the index order of the calling (left) DataFrame

    Notes
    -----
    on, lsuffix, and rsuffix options are not supported when passing a list
    of DataFrame objects

    Returns
    -------
    joined : DataFrame

In [220]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})

In [221]:
left

    A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [222]:
left.join(right,on = ["key1","key2"],how="inner")

Empty DataFrame
Columns: [A, B, key1, key2, C, D]
Index: []

In [224]:
left.join(right,on = ["key1","key2"])   how 的默认是“left”

    A   B key1 key2    C    D
0  A0  B0   K0   K0  NaN  NaN
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0  NaN  NaN
3  A3  B3   K2   K1  NaN  NaN

### 如果两张表的主键都在index上，join的功能就很强大！

In [227]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                     index=pd.Index(['K0', 'K1', 'K2'], name='key'))


index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                 ('K2', 'Y2'), ('K2', 'Y3')],
                                  names=['key', 'Y'])


right = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']},
                      index=index)

In [228]:
left

      A   B
key
K0   A0  B0
K1   A1  B1
K2   A2  B2

In [229]:
right

         C   D
key Y
K0  Y0  C0  D0
K1  Y1  C1  D1
K2  Y2  C2  D2
    Y3  C3  D3

In [230]:
left.join(right) #join 按名称找，不是按顺序找e

         A   B   C   D
key Y
K0  Y0  A0  B0  C0  D0
K1  Y1  A1  B1  C1  D1
K2  Y2  A2  B2  C2  D2
    Y3  A2  B2  C3  D3